/**
 * Full static BetBurger market-type catalog (ids 1..1539, with gaps).
 * `%s` is replaced with market_and_bet_type_param when resolving a leg's
 * market name (Fase 5). Names are kept verbatim from BetBurger (not translated,
 * including upstream quirks). `%s` placeholders are preserved exactly.
 */
export interface BetburgerMarketTypeEntry {
  id: number;
  nameTemplate: string;
}

export const BETBURGER_MARKET_TYPES: BetburgerMarketTypeEntry[] = [
  { id: 1, nameTemplate: 'Team1 Win' },
  { id: 2, nameTemplate: 'Team2 Win' },
  { id: 3, nameTemplate: 'Asian Handicap1(0.0)/Draw No Bet' },
  { id: 4, nameTemplate: 'Asian Handicap2(0.0)/Draw No Bet' },
  { id: 5, nameTemplate: 'European Handicap1(%s)' },
  { id: 6, nameTemplate: 'European HandicapX(%s)' },
  { id: 7, nameTemplate: 'European Handicap2(%s)' },
  { id: 8, nameTemplate: 'Both to score' },
  { id: 9, nameTemplate: 'One scoreless' },
  { id: 11, nameTemplate: '1' },
  { id: 12, nameTemplate: 'X' },
  { id: 13, nameTemplate: '2' },
  { id: 14, nameTemplate: '1X' },
  { id: 15, nameTemplate: 'X2' },
  { id: 16, nameTemplate: '12' },
  { id: 17, nameTemplate: 'Asian Handicap1(%s)' },
  { id: 18, nameTemplate: 'Asian Handicap2(%s)' },
  { id: 19, nameTemplate: 'Total Over(%s)' },
  { id: 20, nameTemplate: 'Total Under(%s)' },
  { id: 21, nameTemplate: 'Total Over(%s) for Team1' },
  { id: 22, nameTemplate: 'Total Under(%s) for Team1' },
  { id: 23, nameTemplate: 'Total Over(%s) for Team2' },
  { id: 24, nameTemplate: 'Total Under(%s) for Team2' },
  { id: 25, nameTemplate: 'Odd' },
  { id: 26, nameTemplate: 'Even' },
  { id: 27, nameTemplate: '1 - Yellow Cards' },
  { id: 28, nameTemplate: 'X - Yellow Cards' },
  { id: 29, nameTemplate: '2 - Yellow Cards' },
  { id: 30, nameTemplate: '1X - Yellow Cards' },
  { id: 31, nameTemplate: '12 - Yellow Cards' },
  { id: 32, nameTemplate: 'X2 - Yellow Cards' },
  { id: 33, nameTemplate: 'Asian Handicap1(%s) - Yellow Cards' },
  { id: 34, nameTemplate: 'Asian Handicap2(%s) - Yellow Cards' },
  { id: 35, nameTemplate: 'Total Over(%s) - Yellow Cards' },
  { id: 36, nameTemplate: 'Total Under(%s) - Yellow Cards' },
  { id: 37, nameTemplate: 'Total Under(%s) for Team1 - Yellow Cards' },
  { id: 38, nameTemplate: 'Total Over(%s) for Team1 - Yellow Cards' },
  { id: 39, nameTemplate: 'Total Under(%s) for Team2 - Yellow Cards' },
  { id: 40, nameTemplate: 'Total Over(%s) for Team2 - Yellow Cards' },
  { id: 41, nameTemplate: 'Even - Yellow Cards' },
  { id: 42, nameTemplate: 'Odd - Yellow Cards' },
  { id: 43, nameTemplate: '1 - Corners' },
  { id: 44, nameTemplate: 'X - Corners' },
  { id: 45, nameTemplate: '2 - Corners' },
  { id: 46, nameTemplate: '1X - Corners' },
  { id: 47, nameTemplate: '12 - Corners' },
  { id: 48, nameTemplate: 'X2 - Corners' },
  { id: 49, nameTemplate: 'Asian Handicap1(%s) - Corners' },
  { id: 50, nameTemplate: 'Asian Handicap2(%s) - Corners' },
  { id: 51, nameTemplate: 'Total Over(%s) - Corners' },
  { id: 52, nameTemplate: 'Total Under(%s) - Corners' },
  { id: 53, nameTemplate: 'Total Under(%s) for Team1 - Corners' },
  { id: 54, nameTemplate: 'Total Over(%s) for Team1 - Corners' },
  { id: 55, nameTemplate: 'Total Under(%s) for Team2 - Corners' },
  { id: 56, nameTemplate: 'Total Over(%s) for Team2 - Corners' },
  { id: 57, nameTemplate: 'Odd - Corners' },
  { id: 58, nameTemplate: 'Even - Corners' },
  { id: 63, nameTemplate: 'Red card - yes' },
  { id: 64, nameTemplate: 'No red card' },
  { id: 65, nameTemplate: 'Penalty - yes' },
  { id: 66, nameTemplate: 'No penalty' },
  { id: 67, nameTemplate: 'Score (%s)' },
  { id: 68, nameTemplate: 'Total Over(%s) - Tie Break' },
  { id: 69, nameTemplate: 'Total Under(%s) - Tie Break' },
  { id: 70, nameTemplate: 'Score (%s) - not' },
  { id: 71, nameTemplate: 'Any substitute to score a goal - yes' },
  { id: 72, nameTemplate: 'Any substitute to score a goal - no' },
  { id: 73, nameTemplate: 'Team1 to win by exactly 1 goal - yes' },
  { id: 74, nameTemplate: 'Team1 to win by exactly 1 goal - no' },
  { id: 75, nameTemplate: 'Team2 to win by exactly 1 goal - yes' },
  { id: 76, nameTemplate: 'Team2 to win by exactly 1 goal - no' },
  { id: 77, nameTemplate: 'Team1 to win by exactly 2 goals - yes' },
  { id: 78, nameTemplate: 'Team1 to win by exactly 2 goals - no' },
  { id: 79, nameTemplate: 'Team1 to win by exactly 3 goals - yes' },
  { id: 80, nameTemplate: 'Team1 to win by exactly 3 goals - no' },
  { id: 81, nameTemplate: 'Team2 to win by exactly 2 goals - yes' },
  { id: 82, nameTemplate: 'Team2 to win by exactly 2 goals - no' },
  { id: 83, nameTemplate: 'Team2 to win by exactly 3 goals - yes' },
  { id: 84, nameTemplate: 'Team2 to win by exactly 3 goals - no' },
  { id: 85, nameTemplate: 'Team1 to win to Nil - yes' },
  { id: 86, nameTemplate: 'Team1 to win to Nil - no' },
  { id: 87, nameTemplate: 'Team2 to win to Nil - yes' },
  { id: 88, nameTemplate: 'Team2 to win to Nil - no' },
  { id: 89, nameTemplate: 'Team1 to win either halves - yes' },
  { id: 90, nameTemplate: 'Team1 to win either halves - no' },
  { id: 91, nameTemplate: 'Team2 to win either halves - yes' },
  { id: 92, nameTemplate: 'Team2 to win either halves - no' },
  { id: 93, nameTemplate: 'Draw in either half - yes' },
  { id: 94, nameTemplate: 'Draw in either half - no' },
  { id: 95, nameTemplate: 'Team1 to win in both halves - yes' },
  { id: 96, nameTemplate: 'Team1 to win in both halves - no' },
  { id: 97, nameTemplate: 'Team2 to win in both halves - yes' },
  { id: 98, nameTemplate: 'Team2 to win in both halves - no' },
  { id: 99, nameTemplate: 'Team1 to win and Total Over 2.5 - yes' },
  { id: 100, nameTemplate: 'Team1 to win and Total Over 2.5 - no' },
  { id: 101, nameTemplate: 'Team1 to win and Total Under 2.5 - yes' },
  { id: 102, nameTemplate: 'Team1 to win and Total Under 2.5 - no' },
  { id: 103, nameTemplate: 'Team2 to win and Total Over 2.5 - yes' },
  { id: 104, nameTemplate: 'Team2 to win and Total Over 2.5 - no' },
  { id: 105, nameTemplate: 'Team2 to win and Total Under 2.5 - yes' },
  { id: 106, nameTemplate: 'Team2 to win and Total Under 2.5 - no' },
  { id: 107, nameTemplate: 'Draw in both half - yes' },
  { id: 108, nameTemplate: 'Draw in both half - no' },
  { id: 109, nameTemplate: 'Draw and Total Over 2.5 - yes' },
  { id: 110, nameTemplate: 'Draw and Total Over 2.5 - no' },
  { id: 111, nameTemplate: 'Draw and Total Under 2.5 - yes' },
  { id: 112, nameTemplate: 'Draw and Total Under 2.5 - no' },
  { id: 113, nameTemplate: 'Goals in both halves - yes' },
  { id: 114, nameTemplate: 'Goals in both halves - no' },
  { id: 115, nameTemplate: 'Team1 to score in both halves - yes' },
  { id: 116, nameTemplate: 'Team1 to score in both halves - no' },
  { id: 117, nameTemplate: 'Team2 to score in both halves - yes' },
  { id: 118, nameTemplate: 'Team2 to score in both halves - no' },
  { id: 119, nameTemplate: 'Double - yes' },
  { id: 120, nameTemplate: 'Double - no' },
  { id: 121, nameTemplate: 'Hattrick - yes' },
  { id: 122, nameTemplate: 'Hattrick - no' },
  { id: 123, nameTemplate: 'Own goal - yes' },
  { id: 124, nameTemplate: 'Own goal - no' },
  { id: 125, nameTemplate: 'Both halves > 1.5 goals - yes' },
  { id: 126, nameTemplate: 'Both halves > 1.5 goals - no' },
  { id: 127, nameTemplate: 'Both halves < 1.5 goals - yes' },
  { id: 128, nameTemplate: 'Both halves < 1.5 goals - no' },
  { id: 129, nameTemplate: 'Sets (%s)' },
  { id: 130, nameTemplate: 'Sets (%s) - not' },
  { id: 131, nameTemplate: 'Asian Handicap1(%s) - Sets' },
  { id: 132, nameTemplate: 'Asian Handicap2(%s) - Sets' },
  { id: 133, nameTemplate: 'Total Over(%s) - Sets' },
  { id: 134, nameTemplate: 'Total Under(%s) - Sets' },
  { id: 135, nameTemplate: 'Team1/Team1' },
  { id: 136, nameTemplate: 'Team1/Team1 - no' },
  { id: 137, nameTemplate: 'Team1/Draw' },
  { id: 138, nameTemplate: 'Team1/Draw - no' },
  { id: 139, nameTemplate: 'Team1/Team2' },
  { id: 140, nameTemplate: 'Team1/Team2 - no' },
  { id: 141, nameTemplate: 'Draw/Team1' },
  { id: 142, nameTemplate: 'Draw/Team1 - no' },
  { id: 143, nameTemplate: 'Draw/Draw' },
  { id: 144, nameTemplate: 'Draw/Draw - no' },
  { id: 145, nameTemplate: 'Draw/Team2' },
  { id: 146, nameTemplate: 'Draw/Team2 - no' },
  { id: 147, nameTemplate: 'Team2/Team1' },
  { id: 148, nameTemplate: 'Team2/Team1 - no' },
  { id: 149, nameTemplate: 'Team2/Draw' },
  { id: 150, nameTemplate: 'Team2/Draw - no' },
  { id: 151, nameTemplate: 'Team2/Team2' },
  { id: 152, nameTemplate: 'Team2/Team2 - no' },
  { id: 153, nameTemplate: 'Exact (%s)' },
  { id: 154, nameTemplate: 'Exact (%s) - no' },
  { id: 155, nameTemplate: 'Exact (%s) for Team1' },
  { id: 156, nameTemplate: 'Exact (%s) for Team1 - no' },
  { id: 157, nameTemplate: 'Exact (%s) for Team2' },
  { id: 158, nameTemplate: 'Exact (%s) for Team2 - no' },
  { id: 159, nameTemplate: 'More goals in the 1st half' },
  { id: 160, nameTemplate: 'Equal goals in halves' },
  { id: 161, nameTemplate: 'More goals in the 2nd half' },
  { id: 162, nameTemplate: '1 half most goals (draw no bet)' },
  { id: 163, nameTemplate: '2 half most goals (draw no bet)' },
  { id: 164, nameTemplate: 'Team1 - 1st goal' },
  { id: 165, nameTemplate: 'No goal' },
  { id: 166, nameTemplate: 'Team2 - 1st goal' },
  { id: 167, nameTemplate: 'Team1 - 1st goal (draw no bet)' },
  { id: 168, nameTemplate: 'Team2 - 1st goal (draw no bet)' },
  { id: 169, nameTemplate: 'Team1 - Last goal' },
  { id: 170, nameTemplate: 'No goal' },
  { id: 171, nameTemplate: 'Team2 - Last goal' },
  { id: 172, nameTemplate: 'Team1 - Last goal (draw no bet)' },
  { id: 173, nameTemplate: 'Team2 - Last goal (draw no bet)' },
  { id: 174, nameTemplate: 'Total Over(%s) - Aces' },
  { id: 175, nameTemplate: 'Total Under(%s) - Aces' },
  { id: 176, nameTemplate: 'Total Over(%s) for Team1 - Aces' },
  { id: 177, nameTemplate: 'Total Under(%s) for Team1 - Aces' },
  { id: 178, nameTemplate: 'Total Over(%s) for Team2 - Aces' },
  { id: 179, nameTemplate: 'Total Under(%s) for Team2 - Aces' },
  { id: 180, nameTemplate: 'Total Over(%s) - Double Faults' },
  { id: 181, nameTemplate: 'Total Under(%s) - Double Faults' },
  { id: 182, nameTemplate: 'Total Over(%s) for Team1 - Double Faults' },
  { id: 183, nameTemplate: 'Total Under(%s) for Team1 - Double Faults' },
  { id: 184, nameTemplate: 'Total Over(%s) for Team2 - Double Faults' },
  { id: 185, nameTemplate: 'Total Under(%s) for Team2 - Double Faults' },
  { id: 186, nameTemplate: 'Total Over(%s) for Team1 - 1st Serve' },
  { id: 187, nameTemplate: 'Total Under(%s) for Team1 - 1st Serve' },
  { id: 188, nameTemplate: 'Total Over(%s) for Team2 - 1st Serve' },
  { id: 189, nameTemplate: 'Total Under(%s) for Team2 - 1st Serve' },
  { id: 190, nameTemplate: 'Asian Handicap1(%s) - Aces' },
  { id: 191, nameTemplate: 'Asian Handicap2(%s) - Aces' },
  { id: 192, nameTemplate: 'Asian Handicap1(%s) - Double Faults' },
  { id: 193, nameTemplate: 'Asian Handicap2(%s) - Double Faults' },
  { id: 194, nameTemplate: 'Asian Handicap1(%s) - 1st Serve' },
  { id: 195, nameTemplate: 'Asian Handicap2(%s) - 1st Serve' },
  { id: 196, nameTemplate: 'Player1 - 1st Ace' },
  { id: 197, nameTemplate: 'Player2 - 1st Ace' },
  { id: 198, nameTemplate: 'Player1 - 1st Double Fault' },
  { id: 199, nameTemplate: 'Player2 - 1st Double Fault' },
  { id: 200, nameTemplate: 'W1 - 1st Break' },
  { id: 201, nameTemplate: 'W2 - 1st Break' },
  { id: 202, nameTemplate: 'Team1 - 1st Break' },
  { id: 203, nameTemplate: 'No break' },
  { id: 204, nameTemplate: 'Team2 - 1st Break' },
  { id: 205, nameTemplate: '6-0 Set - yes' },
  { id: 206, nameTemplate: '6-0 Set - no' },
  { id: 207, nameTemplate: 'Win From Behind - yes' },
  { id: 208, nameTemplate: 'Win From Behind - no' },
  { id: 209, nameTemplate: 'Exact (%s) - Sets' },
  { id: 210, nameTemplate: 'Exact (%s) - Sets - no' },
  { id: 211, nameTemplate: 'Team1 - 1st Corner' },
  { id: 212, nameTemplate: 'No corner' },
  { id: 213, nameTemplate: 'Team2 - 1st Corner' },
  { id: 214, nameTemplate: 'Team1 - Last Corner' },
  { id: 215, nameTemplate: 'No corner' },
  { id: 216, nameTemplate: 'Team2 - Last Corner' },
  { id: 217, nameTemplate: 'Team1 - 1st Yellow card' },
  { id: 218, nameTemplate: 'No yellow card' },
  { id: 219, nameTemplate: 'Team2 - 1st Yellow card' },
  { id: 220, nameTemplate: 'Team1 - Last Yellow card' },
  { id: 221, nameTemplate: 'No yellow card' },
  { id: 222, nameTemplate: 'Team2 - Last Yellow card' },
  { id: 223, nameTemplate: 'Team1 - 1st Offside' },
  { id: 224, nameTemplate: 'No offside' },
  { id: 225, nameTemplate: 'Team2 - 1st Offside' },
  { id: 226, nameTemplate: 'Team1 - Last Offside' },
  { id: 227, nameTemplate: 'No offside' },
  { id: 228, nameTemplate: 'Team2 - Last Offside' },
  { id: 229, nameTemplate: '1st subs - 1 half' },
  { id: 230, nameTemplate: '1st subs - 2 half' },
  { id: 231, nameTemplate: '1st subs - intermission' },
  { id: 232, nameTemplate: '1st goal - 1 half' },
  { id: 233, nameTemplate: '1st goal - 2 half' },
  { id: 234, nameTemplate: 'No goal' },
  { id: 235, nameTemplate: 'Team1 - 1st subs' },
  { id: 236, nameTemplate: 'Team2 - 1st subs' },
  { id: 237, nameTemplate: 'Team1 - Last subs' },
  { id: 238, nameTemplate: 'Team2 - Last subs' },
  { id: 239, nameTemplate: '1 - Shots on goal' },
  { id: 240, nameTemplate: 'X - Shots on goal' },
  { id: 241, nameTemplate: '2 - Shots on goal' },
  { id: 242, nameTemplate: '1X - Shots on goal' },
  { id: 243, nameTemplate: '12 - Shots on goal' },
  { id: 244, nameTemplate: 'X2 - Shots on goal' },
  { id: 245, nameTemplate: 'Asian Handicap1(%s) - Shots on goal' },
  { id: 246, nameTemplate: 'Asian Handicap2(%s) - Shots on goal' },
  { id: 247, nameTemplate: 'Total Over(%s) - Shots on goal' },
  { id: 248, nameTemplate: 'Total Under(%s) - Shots on goal' },
  { id: 249, nameTemplate: 'Total Over(%s) for Team1 - Shots on goal' },
  { id: 250, nameTemplate: 'Total Under(%s) for Team1 - Shots on goal' },
  { id: 251, nameTemplate: 'Total Over(%s) for Team2 - Shots on goal' },
  { id: 252, nameTemplate: 'Total Under(%s) for Team2 - Shots on goal' },
  { id: 253, nameTemplate: 'Odd - Shots on goal' },
  { id: 254, nameTemplate: 'Even - Shots on goal' },
  { id: 255, nameTemplate: '1 - Fouls' },
  { id: 256, nameTemplate: 'X - Fouls' },
  { id: 257, nameTemplate: '2 - Fouls' },
  { id: 258, nameTemplate: '1X - Fouls' },
  { id: 259, nameTemplate: '12 - Fouls' },
  { id: 260, nameTemplate: 'X2 - Fouls' },
  { id: 261, nameTemplate: 'Asian Handicap1(%s) - Fouls' },
  { id: 262, nameTemplate: 'Asian Handicap2(%s) - Fouls' },
  { id: 263, nameTemplate: 'Total Over(%s) - Fouls' },
  { id: 264, nameTemplate: 'Total Under(%s) - Fouls' },
  { id: 265, nameTemplate: 'Total Over(%s) for Team1 - Fouls' },
  { id: 266, nameTemplate: 'Total Under(%s) for Team1 - Fouls' },
  { id: 267, nameTemplate: 'Total Over(%s) for Team2 - Fouls' },
  { id: 268, nameTemplate: 'Total Under(%s) for Team2 - Fouls' },
  { id: 269, nameTemplate: 'Odd - Fouls' },
  { id: 270, nameTemplate: 'Even - Fouls' },
  { id: 271, nameTemplate: '1 - Offsides' },
  { id: 272, nameTemplate: 'X - Offsides' },
  { id: 273, nameTemplate: '2 - Offsides' },
  { id: 274, nameTemplate: '1X - Offsides' },
  { id: 275, nameTemplate: '12 - Offsides' },
  { id: 276, nameTemplate: 'X2 - Offsides' },
  { id: 277, nameTemplate: 'Asian Handicap1(%s) - Offsides' },
  { id: 278, nameTemplate: 'Asian Handicap2(%s) - Offsides' },
  { id: 279, nameTemplate: 'Total Over(%s) - Offsides' },
  { id: 280, nameTemplate: 'Total Under(%s) - Offsides' },
  { id: 281, nameTemplate: 'Total Over(%s) for Team1 - Offsides' },
  { id: 282, nameTemplate: 'Total Under(%s) for Team1 - Offsides' },
  { id: 283, nameTemplate: 'Total Over(%s) for Team2 - Offsides' },
  { id: 284, nameTemplate: 'Total Under(%s) for Team2 - Offsides' },
  { id: 285, nameTemplate: 'Odd - Offsides' },
  { id: 286, nameTemplate: 'Even - Offsides' },
  { id: 287, nameTemplate: 'Team1 to Win From Behind - yes' },
  { id: 288, nameTemplate: 'Team1 to Win From Behind - no' },
  { id: 289, nameTemplate: 'Team2 to Win From Behind - yes' },
  { id: 290, nameTemplate: 'Team2 to Win From Behind - no' },
  { id: 291, nameTemplate: 'Both To Score and W1 - yes' },
  { id: 292, nameTemplate: 'Both To Score and W1 - no' },
  { id: 293, nameTemplate: 'Both To Score and W2 - yes' },
  { id: 294, nameTemplate: 'Both To Score and W2 - no' },
  { id: 295, nameTemplate: 'Both To Score and Draw - yes' },
  { id: 296, nameTemplate: 'Both To Score and Draw - no' },
  { id: 297, nameTemplate: 'Exact (%s) - Added time' },
  { id: 298, nameTemplate: 'Exact (%s) - Added time - no' },
  { id: 299, nameTemplate: 'Total Over(%s) - Added time' },
  { id: 300, nameTemplate: 'Total Under(%s) - Added time' },
  { id: 301, nameTemplate: 'Home No Bet - W2' },
  { id: 302, nameTemplate: 'Home No Bet - Draw' },
  { id: 303, nameTemplate: 'Home No Bet - No Draw' },
  { id: 304, nameTemplate: 'Away No Bet - W1' },
  { id: 305, nameTemplate: 'Away No Bet - Draw' },
  { id: 306, nameTemplate: 'Away No Bet - No Draw' },
  { id: 307, nameTemplate: 'Total Over(%s) - Subs' },
  { id: 308, nameTemplate: 'Total Under(%s) - Subs' },
  { id: 309, nameTemplate: 'Total Over(%s) for Team1 - Subs' },
  { id: 310, nameTemplate: 'Total Under(%s) for Team1 - Subs' },
  { id: 311, nameTemplate: 'Total Over(%s) for Team2 - Subs' },
  { id: 312, nameTemplate: 'Total Under(%s) for Team1 - Subs' },
  { id: 313, nameTemplate: '1 - Ball possession' },
  { id: 314, nameTemplate: 'X - Ball possession' },
  { id: 315, nameTemplate: '2 - Ball possession' },
  { id: 316, nameTemplate: '1X - Ball possession' },
  { id: 317, nameTemplate: '12 - Ball possession' },
  { id: 318, nameTemplate: 'X2 - Ball possession' },
  { id: 319, nameTemplate: 'Asian Handicap1(%s) - Ball possession' },
  { id: 320, nameTemplate: 'Asian Handicap2(%s) - Ball possession' },
  { id: 321, nameTemplate: 'Total Over(%s) for Team1 - Ball possession' },
  { id: 322, nameTemplate: 'Total Under(%s) for Team1 - Ball possession' },
  { id: 323, nameTemplate: 'Total Over(%s) for Team2 - Ball possession' },
  { id: 324, nameTemplate: 'Total Under(%s) for Team2 - Ball possession' },
  { id: 325, nameTemplate: 'W1 - 1st Corner' },
  { id: 326, nameTemplate: 'W2 - 1st Corner' },
  { id: 327, nameTemplate: 'W1 - Last Corner' },
  { id: 328, nameTemplate: 'W2 - Last Corner' },
  { id: 329, nameTemplate: 'W1 - 1st Yellow card' },
  { id: 330, nameTemplate: 'W2 - 1st Yellow card' },
  { id: 331, nameTemplate: 'W1 - Last Yellow card' },
  { id: 332, nameTemplate: 'W2 - Last Yellow card' },
  { id: 333, nameTemplate: 'W1 - 1st Offside' },
  { id: 334, nameTemplate: 'W2 - 1st Offside' },
  { id: 335, nameTemplate: 'W1 - Last Offside' },
  { id: 336, nameTemplate: 'W2 - Last Offside' },
  { id: 337, nameTemplate: 'Home No Bet - No W2' },
  { id: 338, nameTemplate: 'Away No Bet - No W1' },
  { id: 339, nameTemplate: '1X and Total Over 2.5 - yes' },
  { id: 340, nameTemplate: '1X and Total Over 2.5 - no' },
  { id: 341, nameTemplate: '1X and Total Under 2.5 - yes' },
  { id: 342, nameTemplate: '1X and Total Under 2.5 - no' },
  { id: 343, nameTemplate: 'X2 and Total Over 2.5 - yes' },
  { id: 344, nameTemplate: 'X2 and Total Over 2.5 - no' },
  { id: 345, nameTemplate: 'X2 and Total Under 2.5 - yes' },
  { id: 346, nameTemplate: 'X2 and Total Under 2.5 - no' },
  { id: 348, nameTemplate: 'Overtime - yes' },
  { id: 351, nameTemplate: 'Overtime - no' },
  { id: 354, nameTemplate: 'Score Draw - yes' },
  { id: 357, nameTemplate: 'Score Draw - no' },
  { id: 360, nameTemplate: 'Race to 2 - W1' },
  { id: 363, nameTemplate: 'Race to 2 - W2' },
  { id: 366, nameTemplate: 'Race to 2 - Team1' },
  { id: 369, nameTemplate: 'Race to 2 - neither' },
  { id: 372, nameTemplate: 'Race to 2 - Team2' },
  { id: 375, nameTemplate: 'Race to 3 - W1' },
  { id: 378, nameTemplate: 'Race to 3 - W2' },
  { id: 381, nameTemplate: 'Race to 3 - Team1' },
  { id: 384, nameTemplate: 'Race to 3 - neither' },
  { id: 387, nameTemplate: 'Race to 3 - Team2' },
  { id: 390, nameTemplate: 'Race to 4 - W1' },
  { id: 393, nameTemplate: 'Race to 4 - W2' },
  { id: 396, nameTemplate: 'Race to 4 - Team1' },
  { id: 399, nameTemplate: 'Race to 4 - neither' },
  { id: 402, nameTemplate: 'Race to 4 - Team2' },
  { id: 405, nameTemplate: 'Race to 5 - W1' },
  { id: 408, nameTemplate: 'Race to 5 - W2' },
  { id: 411, nameTemplate: 'Race to 5 - Team1' },
  { id: 414, nameTemplate: 'Race to 5 - neither' },
  { id: 417, nameTemplate: 'Race to 5 - Team2' },
  { id: 420, nameTemplate: 'Race to 10 - W1' },
  { id: 423, nameTemplate: 'Race to 10 - W2' },
  { id: 426, nameTemplate: 'Race to 10 - Team1' },
  { id: 429, nameTemplate: 'Race to 10 - neither' },
  { id: 432, nameTemplate: 'Race to 10 - Team2' },
  { id: 435, nameTemplate: 'Race to 15 - W1' },
  { id: 438, nameTemplate: 'Race to 15 - W2' },
  { id: 441, nameTemplate: 'Race to 15 - Team1' },
  { id: 444, nameTemplate: 'Race to 15 - neither' },
  { id: 447, nameTemplate: 'Race to 15 - Team2' },
  { id: 450, nameTemplate: 'Race to 20 - W1' },
  { id: 453, nameTemplate: 'Race to 20 - W2' },
  { id: 456, nameTemplate: 'Race to 20 - Team1' },
  { id: 459, nameTemplate: 'Race to 20 - neither' },
  { id: 462, nameTemplate: 'Race to 20 - Team2' },
  { id: 467, nameTemplate: 'W1 - Next goal' },
  { id: 470, nameTemplate: 'W2 - Next goal' },
  { id: 473, nameTemplate: 'Team1 - Next goal' },
  { id: 476, nameTemplate: 'No goal' },
  { id: 479, nameTemplate: 'Team2 - Next goal' },
  { id: 481, nameTemplate: '1st - yes' },
  { id: 484, nameTemplate: '1st - no' },
  { id: 487, nameTemplate: '1st-3rd - yes' },
  { id: 490, nameTemplate: '1st-3rd - no' },
  { id: 493, nameTemplate: 'W1' },
  { id: 496, nameTemplate: 'W2' },
  { id: 499, nameTemplate: 'TO(%s) - Hits' },
  { id: 502, nameTemplate: 'TU(%s) - Hits' },
  { id: 505, nameTemplate: 'TO(%s) for Team1 - Hits' },
  { id: 508, nameTemplate: 'TU(%s) for Team1 - Hits' },
  { id: 511, nameTemplate: 'TO(%s) for Team2 - Hits' },
  { id: 514, nameTemplate: 'TU(%s) for Team2 - Hits' },
  { id: 517, nameTemplate: 'TO(%s) - Errors' },
  { id: 520, nameTemplate: 'TU(%s) - Errors' },
  { id: 523, nameTemplate: 'TO(%s) - Hits+Errors+Runs' },
  { id: 526, nameTemplate: 'TU(%s) - Hits+Errors+Runs' },
  { id: 529, nameTemplate: 'AH1(%s) - Hits' },
  { id: 532, nameTemplate: 'AH2(%s) - Hits' },
  { id: 535, nameTemplate: '1 - Hits' },
  { id: 538, nameTemplate: 'X - Hits' },
  { id: 541, nameTemplate: '2 - Hits' },
  { id: 546, nameTemplate: 'Team1 Win - Kills' },
  { id: 549, nameTemplate: 'Team2 Win - Kills' },
  { id: 552, nameTemplate: 'Asian Handicap1(%s) - Kills' },
  { id: 555, nameTemplate: 'Asian Handicap2(%s) - Kills' },
  { id: 558, nameTemplate: 'Total Over(%s) - Kills' },
  { id: 561, nameTemplate: 'Total Under(%s) - Kills' },
  { id: 564, nameTemplate: 'Total Over(%s) for Team1 - Kills' },
  { id: 567, nameTemplate: 'Total Under(%s) for Team1 - Kills' },
  { id: 570, nameTemplate: 'Total Over(%s) for Team2 - Kills' },
  { id: 573, nameTemplate: 'Total Under(%s) for Team2 - Kills' },
  { id: 574, nameTemplate: 'W1 - 1st blood' },
  { id: 575, nameTemplate: 'W2 - 1st blood' },
  { id: 576, nameTemplate: 'W1 - 1st tower' },
  { id: 577, nameTemplate: 'W2 - 1st tower' },
  { id: 578, nameTemplate: 'W1 - 1st dragon' },
  { id: 579, nameTemplate: 'W2 - 1st dragon' },
  { id: 580, nameTemplate: 'W1 - 1st baron' },
  { id: 581, nameTemplate: 'W2 - 1st baron' },
  { id: 582, nameTemplate: 'W1 - 1st inhibitor' },
  { id: 583, nameTemplate: 'W2 - 1st inhibitor' },
  { id: 584, nameTemplate: 'W1 - 1st roshan' },
  { id: 585, nameTemplate: 'W2 - 1st roshan' },
  { id: 586, nameTemplate: 'Win pistol rounds - Yes' },
  { id: 587, nameTemplate: 'Win pistol rounds - No' },
  { id: 588, nameTemplate: 'TO(%s) - Duration' },
  { id: 589, nameTemplate: 'TU(%s) - Duration' },
  { id: 590, nameTemplate: 'TO(%s) - Barons' },
  { id: 591, nameTemplate: 'TU(%s) - Barons' },
  { id: 592, nameTemplate: 'TO(%s) - Inhibitors' },
  { id: 593, nameTemplate: 'TU(%s) - Inhibitors' },
  { id: 594, nameTemplate: 'TO(%s) - Towers' },
  { id: 595, nameTemplate: 'TU(%s) - Towers' },
  { id: 596, nameTemplate: 'TO(%s) - Dragons' },
  { id: 597, nameTemplate: 'TU(%s) - Dragons' },
  { id: 598, nameTemplate: 'TO(%s) - Roshans' },
  { id: 599, nameTemplate: 'TU(%s) - Roshans' },
  { id: 600, nameTemplate: 'TO(%s) for Team1 - Sets' },
  { id: 601, nameTemplate: 'TO(%s) for Team1 - Sets' },
  { id: 602, nameTemplate: 'TO(%s) for Team2 - Sets' },
  { id: 603, nameTemplate: 'TO(%s) for Team2 - Sets' },
  { id: 604, nameTemplate: 'W1 - Longest TD' },
  { id: 605, nameTemplate: 'W2 - Longest TD' },
  { id: 606, nameTemplate: 'W1 - Longest FG' },
  { id: 607, nameTemplate: 'W2 - Longest FG' },
  { id: 608, nameTemplate: 'Touchdown - Yes' },
  { id: 609, nameTemplate: 'Touchdown - No' },
  { id: 610, nameTemplate: 'Safety - Yes' },
  { id: 611, nameTemplate: 'Safety - No' },
  { id: 612, nameTemplate: 'First score TD - Yes' },
  { id: 613, nameTemplate: 'First score TD - No' },
  { id: 614, nameTemplate: 'Both teams 10 pts - Yes' },
  { id: 615, nameTemplate: 'Both teams 10 pts - No' },
  { id: 616, nameTemplate: 'Both teams 15 pts - Yes' },
  { id: 617, nameTemplate: 'Both teams 15 pts - No' },
  { id: 618, nameTemplate: 'Both teams 20 pts - Yes' },
  { id: 619, nameTemplate: 'Both teams 20 pts - No' },
  { id: 620, nameTemplate: 'Both teams 25 pts - Yes' },
  { id: 621, nameTemplate: 'Both teams 25 pts - No' },
  { id: 622, nameTemplate: 'Both teams 30 pts - Yes' },
  { id: 623, nameTemplate: 'Both teams 30 pts - No' },
  { id: 624, nameTemplate: 'Both teams 35 pts - Yes' },
  { id: 625, nameTemplate: 'Both teams 35 pts - No' },
  { id: 626, nameTemplate: 'Both teams 40 pts - Yes' },
  { id: 627, nameTemplate: 'Both teams 40 pts - No' },
  { id: 628, nameTemplate: 'Both teams 45 pts - Yes' },
  { id: 629, nameTemplate: 'Both teams 45 pts - No' },
  { id: 630, nameTemplate: 'Both teams 50 pts - Yes' },
  { id: 631, nameTemplate: 'Both teams 50 pts - No' },
  { id: 632, nameTemplate: 'Highest Scoring Quarter - 1st' },
  { id: 633, nameTemplate: 'Highest Scoring Quarter - 2nd' },
  { id: 634, nameTemplate: 'Highest Scoring Quarter - 3rd' },
  { id: 635, nameTemplate: 'Highest Scoring Quarter - 4th' },
  { id: 636, nameTemplate: 'Highest Scoring Quarter - Tie' },
  { id: 637, nameTemplate: 'TO(%s) - Field Goals' },
  { id: 638, nameTemplate: 'TU(%s) - Field Goals' },
  { id: 639, nameTemplate: 'TO(%s) - Touchdowns' },
  { id: 640, nameTemplate: 'TU(%s) - Touchdowns' },
  { id: 641, nameTemplate: 'TO(%s) - Longest TD, distance' },
  { id: 642, nameTemplate: 'TU(%s) - Longest TD, distance' },
  { id: 643, nameTemplate: 'TO(%s) - Longest FG, distance' },
  { id: 644, nameTemplate: 'TU(%s) - Longest FG, distance' },
  { id: 645, nameTemplate: 'TO(%s) for Team1 - Field Goals' },
  { id: 646, nameTemplate: 'TU(%s) for Team1 - Field Goals' },
  { id: 647, nameTemplate: 'TO(%s) for Team2 - Field Goals' },
  { id: 648, nameTemplate: 'TU(%s) for Team2 - Field Goals' },
  { id: 649, nameTemplate: 'TO(%s) for Team1 - Touchdowns' },
  { id: 650, nameTemplate: 'TU(%s) for Team1 - Touchdowns' },
  { id: 651, nameTemplate: 'TO(%s) for Team2 - Touchdowns' },
  { id: 652, nameTemplate: 'TU(%s) for Team2 - Touchdowns' },
  { id: 653, nameTemplate: 'AH1(%s) - Maps' },
  { id: 654, nameTemplate: 'AH2(%s) - Maps' },
  { id: 655, nameTemplate: 'TO(%s) - Maps' },
  { id: 656, nameTemplate: 'TU(%s) - Maps' },
  { id: 657, nameTemplate: 'TO(%s) for Team1 - Maps' },
  { id: 658, nameTemplate: 'TU(%s) for Team1 - Maps' },
  { id: 659, nameTemplate: 'TO(%s) for Team2 - Maps' },
  { id: 660, nameTemplate: 'TU(%s) for Team2 - Maps' },
  { id: 661, nameTemplate: 'Maps (%s)' },
  { id: 662, nameTemplate: 'Maps (%s) - not' },
  { id: 663, nameTemplate: 'Exact (%s) - Maps' },
  { id: 664, nameTemplate: 'Exact (%s) - Maps - no' },
  { id: 665, nameTemplate: 'Win both pistol rounds - Yes' },
  { id: 666, nameTemplate: 'Win both pistol rounds - No' },
  { id: 667, nameTemplate: 'Team1 to win both pistol rounds - Yes' },
  { id: 668, nameTemplate: 'Team1 to win both pistol rounds - No' },
  { id: 669, nameTemplate: 'Team2 to win both pistol rounds - Yes' },
  { id: 670, nameTemplate: 'Team1 to win both pistol rounds - No' },
  { id: 671, nameTemplate: 'Team1 to win at least 1 set - Yes' },
  { id: 672, nameTemplate: 'Team1 to win at least 1 set - No' },
  { id: 673, nameTemplate: 'Team2 to win at least 1 set - Yes' },
  { id: 674, nameTemplate: 'Team1 to win at least 1 set - No' },
  { id: 675, nameTemplate: 'Team1 to win at least 1 map - Yes' },
  { id: 676, nameTemplate: 'Team1 to win at least 1 map - No' },
  { id: 677, nameTemplate: 'Team2 to win at least 1 map - Yes' },
  { id: 678, nameTemplate: 'Team1 to win at least 1 map - No' },
  { id: 679, nameTemplate: 'Both teams kill a dragon - Yes' },
  { id: 680, nameTemplate: 'Both teams kill a dragon - No' },
  { id: 681, nameTemplate: 'Both teams kill a baron - Yes' },
  { id: 682, nameTemplate: 'Both teams kill a baron - No' },
  { id: 683, nameTemplate: 'W1 - 1st Barracks' },
  { id: 684, nameTemplate: 'W2 - 1st Barracks' },
  { id: 685, nameTemplate: 'W1 - 1st Double Kill' },
  { id: 686, nameTemplate: 'W2 - 1st Double Kill' },
  { id: 687, nameTemplate: 'TO(%s) - Barracks' },
  { id: 688, nameTemplate: 'TU(%s) - Barracks' },
  { id: 689, nameTemplate: 'TO(%s) - Double Kills' },
  { id: 690, nameTemplate: 'TU(%s) - Double Kills' },
  { id: 691, nameTemplate: 'AH1(%s) - Barons' },
  { id: 692, nameTemplate: 'AH2(%s) - Barons' },
  { id: 693, nameTemplate: 'AH1(%s) - Dragons' },
  { id: 694, nameTemplate: 'AH2(%s) - Dragons' },
  { id: 695, nameTemplate: 'AH1(%s) - Towers/Turrets' },
  { id: 696, nameTemplate: 'AH2(%s) - Towers/Turrets' },
  { id: 697, nameTemplate: '1 - 3-points' },
  { id: 698, nameTemplate: 'X - 3-points' },
  { id: 699, nameTemplate: '2 - 3-points' },
  { id: 700, nameTemplate: '1 - Rebounds' },
  { id: 701, nameTemplate: 'X - Rebounds' },
  { id: 702, nameTemplate: '2 - Rebounds' },
  { id: 703, nameTemplate: '1 - Assists' },
  { id: 704, nameTemplate: 'X - Assists' },
  { id: 705, nameTemplate: '2 - Assists' },
  { id: 706, nameTemplate: '1X - 3-points' },
  { id: 707, nameTemplate: 'X2 - 3-points' },
  { id: 708, nameTemplate: '12 - 3-points' },
  { id: 709, nameTemplate: '1X - Rebounds' },
  { id: 710, nameTemplate: 'X2 - Rebounds' },
  { id: 711, nameTemplate: '12 - Rebounds' },
  { id: 712, nameTemplate: '1X - Assists' },
  { id: 713, nameTemplate: 'X2 - Assists' },
  { id: 714, nameTemplate: '12 - Assists' },
  { id: 715, nameTemplate: 'AH1(%s) - 3-points' },
  { id: 716, nameTemplate: 'AH2(%s) - 3-points' },
  { id: 717, nameTemplate: 'AH1(%s) - Rebounds' },
  { id: 718, nameTemplate: 'AH2(%s) - Rebounds' },
  { id: 719, nameTemplate: 'AH1(%s) - Assists' },
  { id: 720, nameTemplate: 'AH2(%s) - Assists' },
  { id: 721, nameTemplate: 'TO(%s) - 3-points' },
  { id: 722, nameTemplate: 'TU(%s) - 3-points' },
  { id: 723, nameTemplate: 'TO(%s) - Rebounds' },
  { id: 724, nameTemplate: 'TU(%s) - Rebounds' },
  { id: 725, nameTemplate: 'TO(%s) - Assists' },
  { id: 726, nameTemplate: 'TU(%s) - Assists' },
  { id: 727, nameTemplate: 'TO(%s) for Team1 - 3-points' },
  { id: 728, nameTemplate: 'TU(%s) for Team1 - 3-points' },
  { id: 729, nameTemplate: 'TO(%s) for Team1 - Rebounds' },
  { id: 730, nameTemplate: 'TU(%s) for Team1 - Rebounds' },
  { id: 731, nameTemplate: 'TO(%s) for Team1 - Assists' },
  { id: 732, nameTemplate: 'TU(%s) for Team1 - Assists' },
  { id: 733, nameTemplate: 'TO(%s) for Team2 - 3-points' },
  { id: 734, nameTemplate: 'TU(%s) for Team2 - 3-points' },
  { id: 735, nameTemplate: 'TO(%s) for Team2 - Rebounds' },
  { id: 736, nameTemplate: 'TU(%s) for Team2 - Rebounds' },
  { id: 737, nameTemplate: 'TO(%s) for Team2 - Assists' },
  { id: 738, nameTemplate: 'TU(%s) for Team2 - Assists' },
  { id: 739, nameTemplate: 'W1 - 180s' },
  { id: 740, nameTemplate: 'W2 - 180s' },
  { id: 741, nameTemplate: 'AH1(%s) - 180s' },
  { id: 742, nameTemplate: 'AH2(%s) - 180s' },
  { id: 743, nameTemplate: 'TO(%s) - 180s' },
  { id: 744, nameTemplate: 'TU(%s) - 180s' },
  { id: 745, nameTemplate: '1 - Cards' },
  { id: 746, nameTemplate: 'X - Cards' },
  { id: 747, nameTemplate: '2 - Cards' },
  { id: 748, nameTemplate: '1 - Booking points' },
  { id: 749, nameTemplate: 'X - Booking points' },
  { id: 750, nameTemplate: '2 - Booking points' },
  { id: 751, nameTemplate: '1X - Cards' },
  { id: 752, nameTemplate: 'X2 - Cards' },
  { id: 753, nameTemplate: '12 - Cards' },
  { id: 754, nameTemplate: '1X - Booking points' },
  { id: 755, nameTemplate: 'X2 - Booking points' },
  { id: 756, nameTemplate: '12 - Booking points' },
  { id: 757, nameTemplate: 'AH1(%s) - Cards' },
  { id: 758, nameTemplate: 'AH2(%s) - Cards' },
  { id: 759, nameTemplate: 'AH1(%s) - Booking points' },
  { id: 760, nameTemplate: 'AH2(%s) - Booking points' },
  { id: 761, nameTemplate: 'TO(%s) - Cards' },
  { id: 762, nameTemplate: 'TU(%s) - Cards' },
  { id: 763, nameTemplate: 'TO(%s) - Booking points' },
  { id: 764, nameTemplate: 'TU(%s) - Booking points' },
  { id: 765, nameTemplate: 'TO(%s) for Team1 - Cards' },
  { id: 766, nameTemplate: 'TU(%s) for Team1 - Cards' },
  { id: 767, nameTemplate: 'TO(%s) for Team1 - Booking points' },
  { id: 768, nameTemplate: 'TU(%s) for Team1 - Booking points' },
  { id: 769, nameTemplate: 'TO(%s) for Team2 - Cards' },
  { id: 770, nameTemplate: 'TU(%s) for Team2 - Cards' },
  { id: 771, nameTemplate: 'TO(%s) for Team2 - Booking points' },
  { id: 772, nameTemplate: 'TU(%s) for Team2 - Booking points' },
  { id: 773, nameTemplate: 'Odd - Cards' },
  { id: 774, nameTemplate: 'Even - Cards' },
  { id: 775, nameTemplate: 'Odd - Booking points' },
  { id: 776, nameTemplate: 'Even - Booking points' },
  { id: 777, nameTemplate: 'Odd for Team1' },
  { id: 778, nameTemplate: 'Even for Team1' },
  { id: 779, nameTemplate: 'Odd for Team2' },
  { id: 780, nameTemplate: 'Even for Team2' },
  { id: 781, nameTemplate: 'Over(%s) - 3-way' },
  { id: 782, nameTemplate: 'Exact(%s) - 3-way' },
  { id: 783, nameTemplate: 'Under(%s) - 3-way' },
  { id: 784, nameTemplate: 'Over(%s) for Team1 - 3-way' },
  { id: 785, nameTemplate: 'Exact(%s) for Team1 - 3-way' },
  { id: 786, nameTemplate: 'Under(%s) for Team1 - 3-way' },
  { id: 787, nameTemplate: 'Over(%s) for Team2 - 3-way' },
  { id: 788, nameTemplate: 'Exact(%s) for Team2 - 3-way' },
  { id: 789, nameTemplate: 'Under(%s) for Team2 - 3-way' },
  { id: 790, nameTemplate: 'EH1(%s) - Corners' },
  { id: 791, nameTemplate: 'EHX(%s) - Corners' },
  { id: 792, nameTemplate: 'EH2(%s) - Corners' },
  { id: 793, nameTemplate: 'Odd for Team1 - Corners' },
  { id: 794, nameTemplate: 'Even for Team1 - Corners' },
  { id: 795, nameTemplate: 'Odd for Team2 - Corners' },
  { id: 796, nameTemplate: 'Even for Team2 - Corners' },
  { id: 797, nameTemplate: 'Exact(%s) - Corners' },
  { id: 798, nameTemplate: 'Exact(%s) for Team1 - Corners' },
  { id: 799, nameTemplate: 'Exact(%s) for Team2 - Corners' },
  { id: 800, nameTemplate: 'Over(%s) - 3-way Corners' },
  { id: 801, nameTemplate: 'Exact(%s) - 3-way Corners' },
  { id: 802, nameTemplate: 'Under(%s) - 3-way Corners' },
  { id: 803, nameTemplate: 'Over(%s) for Team1 - 3-way Corners' },
  { id: 804, nameTemplate: 'Exact(%s) for Team1 - 3-way Corners' },
  { id: 805, nameTemplate: 'Under(%s) for Team1 - 3-way Corners' },
  { id: 806, nameTemplate: 'Over(%s) for Team2 - 3-way Corners' },
  { id: 807, nameTemplate: 'Exact(%s) for Team2 - 3-way Corners' },
  { id: 808, nameTemplate: 'Under(%s) for Team2 - 3-way Corners' },
  { id: 809, nameTemplate: 'EH1(%s) - Yellow cards' },
  { id: 810, nameTemplate: 'EHX(%s) - Yellow cards' },
  { id: 811, nameTemplate: 'EH2(%s) - Yellow cards' },
  { id: 812, nameTemplate: 'Odd for Team1 - Yellow cards' },
  { id: 813, nameTemplate: 'Even for Team1 - Yellow cards' },
  { id: 814, nameTemplate: 'Odd for Team2 - Yellow cards' },
  { id: 815, nameTemplate: 'Even for Team2 - Yellow cards' },
  { id: 816, nameTemplate: 'Exact(%s) - Yellow cards' },
  { id: 817, nameTemplate: 'Exact(%s) for Team1 - Yellow cards' },
  { id: 818, nameTemplate: 'Exact(%s) for Team2 - Yellow cards' },
  { id: 819, nameTemplate: 'Over(%s) - 3-way Yellow cards' },
  { id: 820, nameTemplate: 'Exact(%s) - 3-way Yellow cards' },
  { id: 821, nameTemplate: 'Under(%s) - 3-way Yellow cards' },
  { id: 822, nameTemplate: 'EH1(%s) - Cards' },
  { id: 823, nameTemplate: 'EHX(%s) - Cards' },
  { id: 824, nameTemplate: 'EH2(%s) - Cards' },
  { id: 825, nameTemplate: 'Odd for Team1 - Cards' },
  { id: 826, nameTemplate: 'Even for Team1 - Cards' },
  { id: 827, nameTemplate: 'Odd for Team2 - Cards' },
  { id: 828, nameTemplate: 'Even for Team2 - Cards' },
  { id: 829, nameTemplate: 'Exact(%s) - Cards' },
  { id: 830, nameTemplate: 'Exact(%s) for Team1 - Cards' },
  { id: 831, nameTemplate: 'Exact(%s) for Team2 - Cards' },
  { id: 832, nameTemplate: 'Over(%s) - 3-way Cards' },
  { id: 833, nameTemplate: 'Exact(%s) - 3-way Cards' },
  { id: 834, nameTemplate: 'Under(%s) - 3-way Cards' },
  { id: 835, nameTemplate: 'Over(%s) for Team1 - 3-way Cards' },
  { id: 836, nameTemplate: 'Exact(%s) for Team1 - 3-way Cards' },
  { id: 837, nameTemplate: 'Under(%s) for Team1 - 3-way Cards' },
  { id: 838, nameTemplate: 'Over(%s) for Team2 - 3-way Cards' },
  { id: 839, nameTemplate: 'Exact(%s) for Team2 - 3-way Cards' },
  { id: 840, nameTemplate: 'Under(%s) for Team2 - 3-way Cards' },
  { id: 841, nameTemplate: 'EH1(%s) - Booking points' },
  { id: 842, nameTemplate: 'EHX(%s) - Booking points' },
  { id: 843, nameTemplate: 'EH2(%s) - Booking points' },
  { id: 844, nameTemplate: 'Odd for Team1 - Booking points' },
  { id: 845, nameTemplate: 'Even for Team1 - Booking points' },
  { id: 846, nameTemplate: 'Odd for Team2 - Booking points' },
  { id: 847, nameTemplate: 'Even for Team2 - Booking points' },
  { id: 848, nameTemplate: 'Exact(%s) - Booking points' },
  { id: 849, nameTemplate: 'Exact(%s) for Team1 - Booking points' },
  { id: 850, nameTemplate: 'Exact(%s) for Team2 - Booking points' },
  { id: 851, nameTemplate: 'Over(%s) - 3-way Booking points' },
  { id: 852, nameTemplate: 'Exact(%s) - 3-way Booking points' },
  { id: 853, nameTemplate: 'Under(%s) - 3-way Booking points' },
  { id: 854, nameTemplate: 'Over(%s) for Team1 - 3-way Booking points' },
  { id: 855, nameTemplate: 'Exact(%s) for Team1 - 3-way Booking points' },
  { id: 856, nameTemplate: 'Under(%s) for Team1 - 3-way Booking points' },
  { id: 857, nameTemplate: 'Over(%s) for Team2 - 3-way Booking points' },
  { id: 858, nameTemplate: 'Exact(%s) for Team2 - 3-way Booking points' },
  { id: 859, nameTemplate: 'Under(%s) for Team2 - 3-way Booking points' },
  { id: 860, nameTemplate: 'EH1(%s) - Runs' },
  { id: 861, nameTemplate: 'EHX(%s) - Runs' },
  { id: 862, nameTemplate: 'EH2(%s) - Runs' },
  { id: 863, nameTemplate: 'Odd - Runs' },
  { id: 864, nameTemplate: 'Even - Runs' },
  { id: 865, nameTemplate: 'Odd for Team1 - Runs' },
  { id: 866, nameTemplate: 'Even for Team1 - Runs' },
  { id: 867, nameTemplate: 'Odd for Team2 - Runs' },
  { id: 868, nameTemplate: 'Even for Team2 - Runs' },
  { id: 869, nameTemplate: 'Exact(%s) - Runs' },
  { id: 870, nameTemplate: 'Exact(%s) for Team1 - Runs' },
  { id: 871, nameTemplate: 'Exact(%s) for Team2 - Runs' },
  { id: 872, nameTemplate: 'TO(%s) - Runs' },
  { id: 873, nameTemplate: 'TU(%s) - Runs' },
  { id: 874, nameTemplate: 'TO(%s) for Team1 - Runs' },
  { id: 875, nameTemplate: 'TU(%s) for Team1 - Runs' },
  { id: 876, nameTemplate: 'TO(%s) for Team2 - Runs' },
  { id: 877, nameTemplate: 'TU(%s) for Team2 - Runs' },
  { id: 878, nameTemplate: 'Over(%s) - 3-way Runs' },
  { id: 879, nameTemplate: 'Exact(%s) - 3-way Runs' },
  { id: 880, nameTemplate: 'Under(%s) - 3-way Runs' },
  { id: 881, nameTemplate: 'Over(%s) for Team1 - 3-way Runs' },
  { id: 882, nameTemplate: 'Exact(%s) for Team1 - 3-way Runs' },
  { id: 883, nameTemplate: 'Under(%s) for Team1 - 3-way Runs' },
  { id: 884, nameTemplate: 'Over(%s) for Team2 - 3-way Runs' },
  { id: 885, nameTemplate: 'Exact(%s) for Team2 - 3-way Runs' },
  { id: 886, nameTemplate: 'Under(%s) for Team2 - 3-way Runs' },
  { id: 887, nameTemplate: 'W1 - Sixes' },
  { id: 888, nameTemplate: 'W2 - Sixes' },
  { id: 889, nameTemplate: '1 - Sixes' },
  { id: 890, nameTemplate: 'X - Sixes' },
  { id: 891, nameTemplate: '2 - Sixes' },
  { id: 892, nameTemplate: 'TO(%s) - Sixes' },
  { id: 893, nameTemplate: 'TU(%s) - Sixes' },
  { id: 894, nameTemplate: 'TO(%s) for Team1 - Sixes' },
  { id: 895, nameTemplate: 'TU(%s) for Team1 - Sixes' },
  { id: 896, nameTemplate: 'TO(%s) for Team2 - Sixes' },
  { id: 897, nameTemplate: 'TU(%s) for Team2 - Sixes' },
  { id: 898, nameTemplate: 'W1 - Fours' },
  { id: 899, nameTemplate: 'W2 - Fours' },
  { id: 900, nameTemplate: '1 - Fours' },
  { id: 901, nameTemplate: 'X - Fours' },
  { id: 902, nameTemplate: '2 - Fours' },
  { id: 903, nameTemplate: 'TO(%s) - Fours' },
  { id: 904, nameTemplate: 'TU(%s) - Fours' },
  { id: 905, nameTemplate: 'TO(%s) for Team1 - Fours' },
  { id: 906, nameTemplate: 'TU(%s) for Team1 - Fours' },
  { id: 907, nameTemplate: 'TO(%s) for Team2 - Fours' },
  { id: 908, nameTemplate: 'TU(%s) for Team2 - Fours' },
  { id: 909, nameTemplate: 'W1 - Toss' },
  { id: 910, nameTemplate: 'W2 - Toss' },
  { id: 911, nameTemplate: 'W1 - 1st Touchdown' },
  { id: 912, nameTemplate: 'W2 - 1st Touchdown' },
  { id: 913, nameTemplate: 'Team1 - 1st Touchdown' },
  { id: 914, nameTemplate: 'No touchdown' },
  { id: 915, nameTemplate: 'Team2 - 1st Touchdown' },
  { id: 920, nameTemplate: '1 half most corners (no draw)' },
  { id: 921, nameTemplate: '2 half most corners (no draw)' },
  { id: 922, nameTemplate: 'More corners in the first half' },
  { id: 923, nameTemplate: 'Equal corners in halves' },
  { id: 924, nameTemplate: 'More corners in the second half' },
  { id: 925, nameTemplate: '1 half most yellow cards (no draw)' },
  { id: 926, nameTemplate: '2 half most yellow cards (no draw)' },
  { id: 927, nameTemplate: 'More yellow cards in the first half' },
  { id: 928, nameTemplate: 'Equal yellow cards in halves' },
  { id: 929, nameTemplate: 'More yellow cards in the second half' },
  { id: 930, nameTemplate: '1 half most cards (no draw)' },
  { id: 931, nameTemplate: '2 half most cards (no draw)' },
  { id: 932, nameTemplate: 'More cards in the first half' },
  { id: 933, nameTemplate: 'Equal cards in halves' },
  { id: 934, nameTemplate: 'More cards in the second half' },
  { id: 935, nameTemplate: '1 half most booking points (no draw)' },
  { id: 936, nameTemplate: '2 half most booking points (no draw)' },
  { id: 937, nameTemplate: 'More booking points in the first half' },
  { id: 938, nameTemplate: 'Equal booking points in halves' },
  { id: 939, nameTemplate: 'More booking points in the second half' },
  { id: 940, nameTemplate: 'Over(%s) for Team1 - 3-way Yellow cards' },
  { id: 941, nameTemplate: 'Exact(%s) for Team1 - 3-way Yellow cards' },
  { id: 942, nameTemplate: 'Under(%s) for Team1 - 3-way Yellow cards' },
  { id: 943, nameTemplate: 'Over(%s) for Team2 - 3-way Yellow cards' },
  { id: 944, nameTemplate: 'Exact(%s) for Team2 - 3-way Yellow cards' },
  { id: 945, nameTemplate: 'Under(%s) for Team2 - 3-way Yellow cards' },
  { id: 946, nameTemplate: 'Player to Score' },
  { id: 947, nameTemplate: 'Player to Score - No' },
  { id: 948, nameTemplate: 'Player to Score First Goal' },
  { id: 949, nameTemplate: 'Player to Score First Goal - No' },
  { id: 950, nameTemplate: 'Player to Score Exact(%s)' },
  { id: 951, nameTemplate: 'Player to Score Exact(%s) - No' },
  { id: 952, nameTemplate: 'Player to Score Most Goals - Yes' },
  { id: 953, nameTemplate: 'Player to Score Most Goals - No' },
  { id: 954, nameTemplate: 'Player to Score Last Goal' },
  { id: 955, nameTemplate: 'Player to Score Last Goal - No' },
  { id: 956, nameTemplate: 'Player to Score Next Goal' },
  { id: 957, nameTemplate: 'Player to Score Next Goal - No' },
  { id: 958, nameTemplate: 'Player to Score First Goal for Team1' },
  { id: 959, nameTemplate: 'Player to Score First Goal for Team1 - No' },
  { id: 960, nameTemplate: 'Player to Score First Goal for Team2' },
  { id: 961, nameTemplate: 'Player to Score First Goal for Team2 - No' },
  { id: 962, nameTemplate: 'Over(%s) - Player to Score' },
  { id: 963, nameTemplate: 'Under(%s) - Player to Score' },
  { id: 964, nameTemplate: 'Player to be Booked' },
  { id: 965, nameTemplate: 'Player to be Booked - No' },
  { id: 966, nameTemplate: 'Over(%s) - Player Shots on Target' },
  { id: 967, nameTemplate: 'Under(%s) - Player Shots on Target' },
  { id: 968, nameTemplate: 'Player to Assist' },
  { id: 969, nameTemplate: 'Player to Assist - No' },
  { id: 970, nameTemplate: 'Over(%s) - Player Assists' },
  { id: 971, nameTemplate: 'Under(%s) - Player Assists' },
  { id: 972, nameTemplate: 'Over(%s) - Player Rebounds' },
  { id: 973, nameTemplate: 'Under(%s) - Player Rebounds' },
  { id: 974, nameTemplate: 'Over(%s) - Player Steals' },
  { id: 975, nameTemplate: 'Under(%s) - Player Steals' },
  { id: 976, nameTemplate: 'Over(%s) - Player Turnovers' },
  { id: 977, nameTemplate: 'Under(%s) - Player Turnovers' },
  { id: 978, nameTemplate: 'Over(%s) - Player Blocks' },
  { id: 979, nameTemplate: 'Under(%s) - Player Blocks' },
  { id: 980, nameTemplate: 'Over(%s) - Player 3-Points' },
  { id: 981, nameTemplate: 'Under(%s) - Player 3-Points' },
  { id: 982, nameTemplate: 'Over(%s) - Player Runs' },
  { id: 983, nameTemplate: 'Under(%s) - Player Runs' },
  { id: 984, nameTemplate: 'Best Batsman for Team1' },
  { id: 985, nameTemplate: 'Best Batsman for Team1 - No' },
  { id: 986, nameTemplate: 'Best Batsman for Team2' },
  { id: 987, nameTemplate: 'Best Batsman for Team2 - No' },
  { id: 988, nameTemplate: 'Best Bowler for Team1' },
  { id: 989, nameTemplate: 'Best Bowler for Team1 - No' },
  { id: 990, nameTemplate: 'Best Bowler for Team2' },
  { id: 991, nameTemplate: 'Best Bowler for Team2 - No' },
  { id: 992, nameTemplate: 'Player to Score Most Sixes' },
  { id: 993, nameTemplate: 'Player to Score Most Sixes - No' },
  { id: 994, nameTemplate: 'Player to Score Most Fours' },
  { id: 995, nameTemplate: 'Player to Score Most Fours - No' },
  { id: 996, nameTemplate: 'Over(%s) - Player 3-Points' },
  { id: 997, nameTemplate: 'Under(%s) - Player 3-Points' },
  { id: 998, nameTemplate: 'Over(%s) - Player Wickets' },
  { id: 999, nameTemplate: 'Under(%s) - Player Wickets' },
  { id: 1000, nameTemplate: 'Player to Score Fifty' },
  { id: 1001, nameTemplate: 'Player to Score Fifty - No' },
  { id: 1002, nameTemplate: 'Over(%s) - Player Fours' },
  { id: 1003, nameTemplate: 'Under(%s) - Player Fours' },
  { id: 1004, nameTemplate: 'Over(%s) - Player Sixes' },
  { id: 1005, nameTemplate: 'Under(%s) - Player Sixes' },
  { id: 1006, nameTemplate: 'Player to Score Next Touchdown for Team1' },
  { id: 1007, nameTemplate: 'Player to Score Next Touchdown for Team1 - No' },
  { id: 1008, nameTemplate: 'Player to Score Next Touchdown for Team2' },
  { id: 1009, nameTemplate: 'Player to Score Next Touchdown for Team2 - No' },
  { id: 1010, nameTemplate: 'Player to Score First Touchdown' },
  { id: 1011, nameTemplate: 'Player to Score First Touchdown - No' },
  { id: 1012, nameTemplate: 'Player to Score Touchdown' },
  { id: 1013, nameTemplate: 'Player to Score Touchdown - No' },
  { id: 1014, nameTemplate: 'Player to Score Exact(%s) Touchdowns' },
  { id: 1015, nameTemplate: 'Player to Score Exact(%s) Touchdowns - No' },
  { id: 1016, nameTemplate: 'Over(%s) - Player StrikeOuts' },
  { id: 1017, nameTemplate: 'Under(%s) - Player StrikeOuts' },
  { id: 1018, nameTemplate: 'Ply Hitalw Ou To' },
  { id: 1019, nameTemplate: 'Ply Hitalw Ou Tu' },
  { id: 1020, nameTemplate: 'Pitcher to Win' },
  { id: 1021, nameTemplate: 'Pitcher to Win - No' },
  { id: 1022, nameTemplate: 'Over(%s) - Player Outs' },
  { id: 1023, nameTemplate: 'Under(%s) - Player Outs' },
  { id: 1024, nameTemplate: 'Over(%s) - Player Singles' },
  { id: 1025, nameTemplate: 'Under(%s) - Player Singles' },
  { id: 1026, nameTemplate: 'Over(%s) - Player Home Runs' },
  { id: 1027, nameTemplate: 'Under(%s) - Player Home Runs' },
  { id: 1028, nameTemplate: 'Over(%s) - Player Stolen Bases' },
  { id: 1029, nameTemplate: 'Under(%s) - Player Stolen Bases' },
  { id: 1030, nameTemplate: 'Over(%s) - Player Doubles' },
  { id: 1031, nameTemplate: 'Under(%s) - Player Doubles' },
  { id: 1032, nameTemplate: 'Over(%s) - Player Triples' },
  { id: 1033, nameTemplate: 'Under(%s) - Player Triples' },
  { id: 1034, nameTemplate: 'Over(%s) - Player Bases' },
  { id: 1035, nameTemplate: 'Under(%s) - Player Bases' },
  { id: 1036, nameTemplate: 'Over(%s) - 2-min Penalty' },
  { id: 1037, nameTemplate: 'Under(%s) - 2-min Penalty' },
  { id: 1038, nameTemplate: 'Over(%s) - Power Play Goals' },
  { id: 1039, nameTemplate: 'Under(%s) - Power Play Goals' },
  { id: 1040, nameTemplate: 'Over(%s) - Faceoffs' },
  { id: 1041, nameTemplate: 'Under(%s) - Faceoffs' },
  { id: 1042, nameTemplate: 'Over(%s) - Video Referee' },
  { id: 1043, nameTemplate: 'Under(%s) - Video Referee' },
  { id: 1044, nameTemplate: 'Player to Score Try' },
  { id: 1045, nameTemplate: 'Player to Score Try - No' },
  { id: 1046, nameTemplate: 'Player to Score First Try' },
  { id: 1047, nameTemplate: 'Player to Score First Try - No' },
  { id: 1048, nameTemplate: 'Over(%s) - Player Tries' },
  { id: 1049, nameTemplate: 'Under(%s) - Player Tries' },
  { id: 1050, nameTemplate: 'Over(%s) - Player Tries for Team1' },
  { id: 1051, nameTemplate: 'Under(%s) - Player Tries for Team1' },
  { id: 1052, nameTemplate: 'Over(%s) - Player Tries for Team2' },
  { id: 1053, nameTemplate: 'Under(%s) - Player Tries for Team2' },
  { id: 1054, nameTemplate: 'Over(%s) - Player Passing Yards' },
  { id: 1055, nameTemplate: 'Under(%s) - Player Passing Yards' },
  { id: 1056, nameTemplate: 'Over(%s) - Player Passing Yards for Team1' },
  { id: 1057, nameTemplate: 'Under(%s) - Player Passing Yards for Team1' },
  { id: 1058, nameTemplate: 'Over(%s) - Player Passing Yards for Team2' },
  { id: 1059, nameTemplate: 'Under(%s) - Player Passing Yards for Team2' },
  { id: 1060, nameTemplate: 'Over(%s) - Player Rushing Yards' },
  { id: 1061, nameTemplate: 'Under(%s) - Player Rushing Yards' },
  { id: 1062, nameTemplate: 'Over(%s) - Player Rushing Yards for Team1' },
  { id: 1063, nameTemplate: 'Under(%s) - Player Rushing Yards for Team1' },
  { id: 1064, nameTemplate: 'Over(%s) - Player Rushing Yards for Team2' },
  { id: 1065, nameTemplate: 'Under(%s) - Player Rushing Yards for Team2' },
  { id: 1066, nameTemplate: 'Over(%s) - Player Passing Attempts' },
  { id: 1067, nameTemplate: 'Under(%s) - Player Passing Attempts' },
  { id: 1068, nameTemplate: 'Over(%s) - Player Passing Attempts for Team1' },
  { id: 1069, nameTemplate: 'Under(%s) - Player Passing Attempts for Team1' },
  { id: 1070, nameTemplate: 'Over(%s) - Player Passing Attempts for Team2' },
  { id: 1071, nameTemplate: 'Under(%s) - Player Passing Attempts for Team2' },
  { id: 1072, nameTemplate: 'Over(%s) - Player Passing Touchdowns' },
  { id: 1073, nameTemplate: 'Under(%s) - Player Passing Touchdowns' },
  { id: 1074, nameTemplate: 'Over(%s) - Player Passing Touchdowns for Team1' },
  { id: 1075, nameTemplate: 'Under(%s) - Player Passing Touchdowns for Team1' },
  { id: 1076, nameTemplate: 'Over(%s) - Player Passing Touchdowns for Team2' },
  { id: 1077, nameTemplate: 'Under(%s) - Player Passing Touchdowns for Team2' },
  { id: 1078, nameTemplate: 'Over(%s) - Player Receptions' },
  { id: 1079, nameTemplate: 'Under(%s) - Player Receptions' },
  { id: 1080, nameTemplate: 'Over(%s) - Player Receptions for Team1' },
  { id: 1081, nameTemplate: 'Under(%s) - Player Receptions for Team1' },
  { id: 1082, nameTemplate: 'Over(%s) - Player Receptions for Team2' },
  { id: 1083, nameTemplate: 'Under(%s) - Player Receptions for Team2' },
  { id: 1084, nameTemplate: 'Over(%s) - Player Touchdowns' },
  { id: 1085, nameTemplate: 'Under(%s) - Player Touchdowns' },
  { id: 1086, nameTemplate: 'Over(%s) - Player Touchdowns for Team1' },
  { id: 1087, nameTemplate: 'Under(%s) - Player Touchdowns for Team1' },
  { id: 1088, nameTemplate: 'Over(%s) - Player Touchdowns for Team2' },
  { id: 1089, nameTemplate: 'Under(%s) - Player Touchdowns for Team2' },
  { id: 1090, nameTemplate: 'Over(%s) - Player Receiving Attempts' },
  { id: 1091, nameTemplate: 'Under(%s) - Player Receiving Attempts' },
  { id: 1092, nameTemplate: 'Over(%s) - Player Receiving Attempts for Team1' },
  { id: 1093, nameTemplate: 'Under(%s) - Player Receiving Attempts for Team1' },
  { id: 1094, nameTemplate: 'Over(%s) - Player Receiving Attempts for Team2' },
  { id: 1095, nameTemplate: 'Under(%s) - Player Receiving Attempts for Team2' },
  { id: 1096, nameTemplate: 'Over(%s) - Player Rushing Attempts' },
  { id: 1097, nameTemplate: 'Under(%s) - Player Rushing Attempts' },
  { id: 1098, nameTemplate: 'Over(%s) - Player Rushing Attempts for Team1' },
  { id: 1099, nameTemplate: 'Under(%s) - Player Rushing Attempts for Team1' },
  { id: 1100, nameTemplate: 'Over(%s) - Player Rushing Attempts for Team2' },
  { id: 1101, nameTemplate: 'Under(%s) - Player Rushing Attempts for Team2' },
  { id: 1102, nameTemplate: 'Over(%s) - Player Rushing Touchdowns' },
  { id: 1103, nameTemplate: 'Under(%s) - Player Rushing Touchdowns' },
  { id: 1104, nameTemplate: 'Over(%s) - Player Rushing Touchdowns for Team1' },
  { id: 1105, nameTemplate: 'Under(%s) - Player Rushing Touchdowns for Team1' },
  { id: 1106, nameTemplate: 'Over(%s) - Player Rushing Touchdowns for Team2' },
  { id: 1107, nameTemplate: 'Under(%s) - Player Rushing Touchdowns for Team2' },
  { id: 1108, nameTemplate: 'Over(%s) - Player Receiving Touchdowns' },
  { id: 1109, nameTemplate: 'Under(%s) - Player Receiving Touchdowns' },
  {
    id: 1110,
    nameTemplate: 'Over(%s) - Player Receiving Touchdowns for Team1',
  },
  {
    id: 1111,
    nameTemplate: 'Under(%s) - Player Receiving Touchdowns for Team1',
  },
  {
    id: 1112,
    nameTemplate: 'Over(%s) - Player Receiving Touchdowns for Team2',
  },
  {
    id: 1113,
    nameTemplate: 'Under(%s) - Player Receiving Touchdowns for Team2',
  },
  { id: 1114, nameTemplate: 'Player to score last touchdown' },
  { id: 1115, nameTemplate: 'Player to score last touchdown - No' },
  { id: 1116, nameTemplate: 'Player to record a stolen base' },
  { id: 1117, nameTemplate: 'Player to record a stolen base - No' },
  { id: 1118, nameTemplate: 'Over(%s) - Player Goals for Team1' },
  { id: 1119, nameTemplate: 'Under(%s) - Player Goals for Team1' },
  { id: 1120, nameTemplate: 'Over(%s) - Player Goals for Team2' },
  { id: 1121, nameTemplate: 'Under(%s) - Player Goals for Team2' },
  { id: 1122, nameTemplate: 'Player to receive a red card' },
  { id: 1123, nameTemplate: 'Player to receive a red card - No' },
  { id: 1124, nameTemplate: 'Over(%s) - Player Behinds' },
  { id: 1125, nameTemplate: 'Under(%s) - Player Behinds' },
  { id: 1126, nameTemplate: 'Over(%s) - Player Behinds for Team1' },
  { id: 1127, nameTemplate: 'Under(%s) - Player Behinds for Team1' },
  { id: 1128, nameTemplate: 'Over(%s) - Player Behinds for Team2' },
  { id: 1129, nameTemplate: 'Under(%s) - Player Behinds for Team2' },
  { id: 1130, nameTemplate: 'Over(%s) - Player Hits for Team1' },
  { id: 1131, nameTemplate: 'Under(%s) - Player Hits for Team1' },
  { id: 1132, nameTemplate: 'Over(%s) - Player Hits for Team2' },
  { id: 1133, nameTemplate: 'Under(%s) - Player Hits for Team2' },
  { id: 1134, nameTemplate: 'Top team runscorer' },
  { id: 1135, nameTemplate: 'Top team runscorer - No' },
  { id: 1136, nameTemplate: 'Player of the match' },
  { id: 1137, nameTemplate: 'Player of the match - No' },
  { id: 1138, nameTemplate: 'Player of the series' },
  { id: 1139, nameTemplate: 'Player of the series - No' },
  { id: 1140, nameTemplate: 'More goals in the 1st half' },
  { id: 1141, nameTemplate: 'More goals in the 2nd half' },
  { id: 1142, nameTemplate: 'Equal goals in halves' },
  { id: 1143, nameTemplate: '1 half most goals (no draw)' },
  { id: 1144, nameTemplate: '2 half most goals (no draw)' },
  { id: 1145, nameTemplate: 'More corners in the 1st half' },
  { id: 1146, nameTemplate: 'More corners in the 2nd half' },
  { id: 1147, nameTemplate: 'Equal corners in halves' },
  { id: 1148, nameTemplate: '1 half most corners (no draw)' },
  { id: 1149, nameTemplate: '2 half most corners (no draw)' },
  { id: 1150, nameTemplate: 'More yellow cards in the 1st half' },
  { id: 1151, nameTemplate: 'More yellow cards in the 2nd half' },
  { id: 1152, nameTemplate: 'Equal yellow cards in halves' },
  { id: 1153, nameTemplate: '1 half most yellow cards (no draw)' },
  { id: 1154, nameTemplate: '2 half most yellow cards (no draw)' },
  { id: 1155, nameTemplate: 'More cards in the 1st half' },
  { id: 1156, nameTemplate: 'More cards in the 2nd half' },
  { id: 1157, nameTemplate: 'Equal cards in halves' },
  { id: 1158, nameTemplate: '1 half most cards (no draw)' },
  { id: 1159, nameTemplate: '2 half most cards (no draw)' },
  { id: 1160, nameTemplate: 'More booking points in the 1st half' },
  { id: 1161, nameTemplate: 'More booking points in the 2nd half' },
  { id: 1162, nameTemplate: 'Equal booking points in halves' },
  { id: 1163, nameTemplate: '1 half most booking points (no draw)' },
  { id: 1164, nameTemplate: '2 half most booking points (no draw)' },
  { id: 1165, nameTemplate: 'Team1 - 1st goal' },
  { id: 1166, nameTemplate: 'Team2 - 1st goal' },
  { id: 1167, nameTemplate: 'No goal' },
  { id: 1168, nameTemplate: 'W1 - 1st goal' },
  { id: 1169, nameTemplate: 'W2 - 1st goal' },
  { id: 1170, nameTemplate: 'Team1 - Last goal' },
  { id: 1171, nameTemplate: 'Team2 - Last goal' },
  { id: 1172, nameTemplate: 'No goal' },
  { id: 1173, nameTemplate: 'W1 - Last goal' },
  { id: 1174, nameTemplate: 'W2 - Last goal' },
  { id: 1175, nameTemplate: 'Odd - Sets' },
  { id: 1176, nameTemplate: 'Even - Sets' },
  { id: 1177, nameTemplate: 'Over(%s) - 3-way Sets' },
  { id: 1178, nameTemplate: 'Exact(%s) - 3-way Sets' },
  { id: 1179, nameTemplate: 'Under(%s) - 3-way Sets' },
  { id: 1180, nameTemplate: '1 - Shots (All)' },
  { id: 1181, nameTemplate: 'X - Shots (All)' },
  { id: 1182, nameTemplate: '2 - Shots (All)' },
  { id: 1183, nameTemplate: '1X - Shots (All)' },
  { id: 1184, nameTemplate: '12 - Shots (All)' },
  { id: 1185, nameTemplate: 'X2 - Shots (All)' },
  { id: 1186, nameTemplate: 'AH1(%s) - Shots (All)' },
  { id: 1187, nameTemplate: 'AH2(%s) - Shots (All)' },
  { id: 1188, nameTemplate: 'TO(%s) - Shots (All)' },
  { id: 1189, nameTemplate: 'TU(%s) - Shots (All)' },
  { id: 1190, nameTemplate: 'TO(%s) for Team1 - Shots (All)' },
  { id: 1191, nameTemplate: 'TU(%s) for Team1 - Shots (All)' },
  { id: 1192, nameTemplate: 'TO(%s) for Team2 - Shots (All)' },
  { id: 1193, nameTemplate: 'TU(%s) for Team2 - Shots (All)' },
  { id: 1194, nameTemplate: 'Odd - Shots (All)' },
  { id: 1195, nameTemplate: 'Even - Shots (All)' },
  { id: 1196, nameTemplate: 'Home Winning Margin - Exact(%s)' },
  { id: 1197, nameTemplate: 'Home Winning Margin - Exact(%s) - No' },
  { id: 1198, nameTemplate: 'Away Winning Margin - Exact(%s)' },
  { id: 1199, nameTemplate: 'Away Winning Margin - Exact(%s) - No' },
  { id: 1200, nameTemplate: 'Any Team Winning Margin - Exact(%s)' },
  { id: 1201, nameTemplate: 'Any Team Winning Margin - Exact(%s) - No' },
  { id: 1202, nameTemplate: 'Race To (%s) - 3Way - Home Win' },
  { id: 1203, nameTemplate: 'Race To (%s) - 3Way - Draw' },
  { id: 1204, nameTemplate: 'Race To (%s) - 3Way - Away Win' },
  { id: 1205, nameTemplate: 'Race To (%s) - 2Way - Home Win' },
  { id: 1206, nameTemplate: 'Race To (%s) - 2Way - Away Win' },
  { id: 1207, nameTemplate: 'Race To (%s) Hits - 3Way - Home Win' },
  { id: 1208, nameTemplate: 'Race To (%s) Hits - 3Way - Draw' },
  { id: 1209, nameTemplate: 'Race To (%s) Hits - 3Way - Away Win' },
  { id: 1210, nameTemplate: 'Both To Score (%s) - Yes' },
  { id: 1211, nameTemplate: 'Both To Score (%s) - No' },
  { id: 1212, nameTemplate: 'Next Touchdown (%s) - 3Way - Home Win' },
  { id: 1213, nameTemplate: 'Next Touchdown (%s) - 3Way - Draw' },
  { id: 1214, nameTemplate: 'Next Touchdown (%s) - 3Way - Away Win' },
  { id: 1215, nameTemplate: 'Next Field Goal (%s) - 3Way - Home win' },
  { id: 1216, nameTemplate: 'Next Field Goal (%s) - 3Way - Draw' },
  { id: 1217, nameTemplate: 'Next Field Goal (%s) - 3Way - Away Win' },
  { id: 1218, nameTemplate: '(%s) in a Row - Yes' },
  { id: 1219, nameTemplate: '(%s) in a Row - No' },
  { id: 1220, nameTemplate: '1/FullTime - 1/1' },
  { id: 1221, nameTemplate: '1/FullTime - 1/2' },
  { id: 1222, nameTemplate: '1/FullTime - 2/2' },
  { id: 1223, nameTemplate: '1/FullTime - 2/1' },
  { id: 1224, nameTemplate: 'Win1 and TO(%s) - Yes' },
  { id: 1225, nameTemplate: 'Win1 and TO(%s) - No' },
  { id: 1226, nameTemplate: 'Win1 and TU(%s) - Yes' },
  { id: 1227, nameTemplate: 'Win1 and TU(%s) - No' },
  { id: 1228, nameTemplate: 'Eg Win1 Eg' },
  { id: 1229, nameTemplate: 'Eg Win1 Eg N' },
  { id: 1230, nameTemplate: 'Win2 and TO(%s) - Yes' },
  { id: 1231, nameTemplate: 'Win2 and TO(%s) - No' },
  { id: 1232, nameTemplate: 'Win2 and TU(%s) - Yes' },
  { id: 1233, nameTemplate: 'Win2 and TU(%s) - No' },
  { id: 1234, nameTemplate: 'Eg Win2 Eg' },
  { id: 1235, nameTemplate: 'Eg Win2 Eg N' },
  { id: 1236, nameTemplate: 'Draw and TO(%s) - Yes' },
  { id: 1237, nameTemplate: 'Draw and TO(%s) - No' },
  { id: 1238, nameTemplate: 'Draw and TU(%s) - Yes' },
  { id: 1239, nameTemplate: 'Draw and TU(%s) - No' },
  { id: 1240, nameTemplate: 'Eg Draw Eg' },
  { id: 1241, nameTemplate: 'Eg Draw Eg N' },
  { id: 1242, nameTemplate: '1X and TO(%s) - Yes' },
  { id: 1243, nameTemplate: '1X and TO(%s) - No' },
  { id: 1244, nameTemplate: '1X and TU(%s) - Yes' },
  { id: 1245, nameTemplate: '1X and TU(%s) - No' },
  { id: 1246, nameTemplate: 'Eg X1 Eg' },
  { id: 1247, nameTemplate: 'Eg X1 Eg N' },
  { id: 1248, nameTemplate: '12 and TO(%s) - Yes' },
  { id: 1249, nameTemplate: '12 and TO(%s) - No' },
  { id: 1250, nameTemplate: '12 and TU(%s) - Yes' },
  { id: 1251, nameTemplate: '12 and TU(%s) - No' },
  { id: 1252, nameTemplate: 'Eg 12 Eg' },
  { id: 1253, nameTemplate: 'Eg 12 Eg N' },
  { id: 1254, nameTemplate: 'X2 and TO(%s) - Yes' },
  { id: 1255, nameTemplate: 'X2 and TO(%s) - No' },
  { id: 1256, nameTemplate: 'X2 and TU(%s) - Yes' },
  { id: 1257, nameTemplate: 'X2 and TU(%s) - No' },
  { id: 1258, nameTemplate: 'Eg X2 Eg' },
  { id: 1259, nameTemplate: 'Eg X2 Eg N' },
  { id: 1260, nameTemplate: 'Both to Score Yes and TO(%s) - Yes' },
  { id: 1261, nameTemplate: 'Both to Score Yes and TO(%s) - No' },
  { id: 1262, nameTemplate: 'Both to Score Yes and TU(%s) - Yes' },
  { id: 1263, nameTemplate: 'Both to Score Yes and TU(%s) - No' },
  { id: 1264, nameTemplate: 'Both to Score No and TO(%s) - Yes' },
  { id: 1265, nameTemplate: 'Both to Score No and TO(%s) - No' },
  { id: 1266, nameTemplate: 'Both to Score No and TU(%s) - Yes' },
  { id: 1267, nameTemplate: 'Both to Score No and TU(%s) - No' },
  { id: 1268, nameTemplate: 'Both to Score No and Team1 Win - Yes' },
  { id: 1269, nameTemplate: 'Both to Score No and Team1 Win - No' },
  { id: 1270, nameTemplate: 'Both to Score No and Team2 Win - Yes' },
  { id: 1271, nameTemplate: 'Both to Score No and Team2 Win - No' },
  { id: 1272, nameTemplate: 'Both to Score No and Draw - Yes' },
  { id: 1273, nameTemplate: 'Both to Score No and Draw - No' },
  { id: 1274, nameTemplate: 'Both to Score (%s) Points and Win1 - Yes' },
  { id: 1275, nameTemplate: 'Both to Score (%s) Points and Win1 - No' },
  { id: 1276, nameTemplate: 'Both to Score (%s) Points and Win2 - Yes' },
  { id: 1277, nameTemplate: 'Both to Score (%s) Points and Win2 - No' },
  { id: 1278, nameTemplate: 'Both to Score (%s) Points and Draw - Yes' },
  { id: 1279, nameTemplate: 'Both to Score (%s) Points and Draw - No' },
  { id: 1280, nameTemplate: 'TO(%s) - Passing Yards' },
  { id: 1281, nameTemplate: 'TU(%s) - Passing Yards' },
  { id: 1282, nameTemplate: 'TO(%s) - Passing Touchdowns' },
  { id: 1283, nameTemplate: 'TU(%s) - Passing Touchdowns' },
  { id: 1284, nameTemplate: 'TO(%s) - Passing Attempts' },
  { id: 1285, nameTemplate: 'TU(%s) - Passing Attempts' },
  { id: 1286, nameTemplate: 'TO(%s) - Passing Completions' },
  { id: 1287, nameTemplate: 'TU(%s) - Passing Completions' },
  { id: 1288, nameTemplate: 'TO(%s) - Rushing Yards' },
  { id: 1289, nameTemplate: 'TU(%s) - Rushing Yards' },
  { id: 1290, nameTemplate: 'TO(%s) - Rushing Touchdowns' },
  { id: 1291, nameTemplate: 'TU(%s) - Rushing Touchdowns' },
  { id: 1292, nameTemplate: 'TO(%s) - Rushing Attempts' },
  { id: 1293, nameTemplate: 'TU(%s) - Rushing Attempts' },
  { id: 1294, nameTemplate: 'TO(%s) - Sacks' },
  { id: 1295, nameTemplate: 'TU(%s) - Sacks' },
  { id: 1296, nameTemplate: 'TO(%s) - Tackles & Assists' },
  { id: 1297, nameTemplate: 'TU(%s) - Tackles & Assists' },
  { id: 1298, nameTemplate: 'TO(%s) - Receiving & Rushing Yards' },
  { id: 1299, nameTemplate: 'TU(%s) - Receiving & Rushing Yards' },
  { id: 1300, nameTemplate: 'TO(%s) - Punts' },
  { id: 1301, nameTemplate: 'TU(%s) - Punts' },
  { id: 1302, nameTemplate: 'TO(%s) - Home Runs' },
  { id: 1303, nameTemplate: 'TU(%s) - Home Runs' },
  { id: 1304, nameTemplate: 'TO(%s) - Saves' },
  { id: 1305, nameTemplate: 'TU(%s) - Saves' },
  { id: 1306, nameTemplate: 'TO(%s) - Tackles' },
  { id: 1307, nameTemplate: 'TU(%s) - Tackles' },
  { id: 1308, nameTemplate: 'TO(%s) for Team1 - Rushing Yards' },
  { id: 1309, nameTemplate: 'TU(%s) for Team1 - Rushing Yards' },
  { id: 1310, nameTemplate: 'TO(%s) for Team2 - Rushing Yards' },
  { id: 1311, nameTemplate: 'TU(%s) for Team2 - Rushing Yards' },
  { id: 1312, nameTemplate: 'TO(%s) for Team1 - Rushing Touchdowns' },
  { id: 1313, nameTemplate: 'TU(%s) for Team1 - Rushing Touchdowns' },
  { id: 1314, nameTemplate: 'TO(%s) for Team2 - Rushing Touchdowns' },
  { id: 1315, nameTemplate: 'TU(%s) for Team2 - Rushing Touchdowns' },
  { id: 1316, nameTemplate: 'TO(%s) for Team1 - Rushing Attempts' },
  { id: 1317, nameTemplate: 'TU(%s) for Team1 - Rushing Attempts' },
  { id: 1318, nameTemplate: 'TO(%s) for Team2 - Rushing Attempts' },
  { id: 1319, nameTemplate: 'TU(%s) for Team2 - Rushing Attempts' },
  { id: 1320, nameTemplate: 'TO(%s) for Team1 - Sacks' },
  { id: 1321, nameTemplate: 'TU(%s) for Team1 - Sacks' },
  { id: 1322, nameTemplate: 'TO(%s) for Team2 - Sacks' },
  { id: 1323, nameTemplate: 'TU(%s) for Team2 - Sacks' },
  { id: 1324, nameTemplate: 'TO(%s) for Team1 - Receiving & Rushing Yards' },
  { id: 1325, nameTemplate: 'TU(%s) for Team1 - Receiving & Rushing Yards' },
  { id: 1326, nameTemplate: 'TO(%s) for Team2 - Receiving & Rushing Yards' },
  { id: 1327, nameTemplate: 'TU(%s) for Team2 - Receiving & Rushing Yards' },
  { id: 1328, nameTemplate: 'Score in Each Period - Yes' },
  { id: 1329, nameTemplate: 'Score in Each Period - No' },
  { id: 1330, nameTemplate: 'Team1 To Score Every Period - Yes' },
  { id: 1331, nameTemplate: 'Team1 To Score Every Period - No' },
  { id: 1332, nameTemplate: 'Team2 To Score Every Period - Yes' },
  { id: 1333, nameTemplate: 'Team2 To Score Every Period - No' },
  { id: 1334, nameTemplate: 'Team1 to Win All Periods - Yes' },
  { id: 1335, nameTemplate: 'Team1 to Win All Periods - No' },
  { id: 1336, nameTemplate: 'Team2 to Win All Periods - Yes' },
  { id: 1337, nameTemplate: 'Team2 to Win All Periods - No' },
  { id: 1338, nameTemplate: 'Scoreless Period - Yes' },
  { id: 1339, nameTemplate: 'Scoreless Period - No' },
  { id: 1340, nameTemplate: 'Quarters (%s)' },
  { id: 1341, nameTemplate: 'Quarters (%s) - not' },
  { id: 1342, nameTemplate: 'TO(%s) - Shortest TD, distance' },
  { id: 1343, nameTemplate: 'TU(%s) - Shortest TD, distance' },
  { id: 1344, nameTemplate: 'TO(%s) - Shortest FG, distance' },
  { id: 1345, nameTemplate: 'TU(%s) - Shortest FG, distance' },
  { id: 1346, nameTemplate: 'Defensive or Special Teams Touchdown - Yes' },
  { id: 1347, nameTemplate: 'Defensive or Special Teams Touchdown - No' },
  { id: 1348, nameTemplate: 'Successful 2 Point Conversion - Yes' },
  { id: 1349, nameTemplate: 'Successful 2 Point Conversion - No' },
  { id: 1350, nameTemplate: 'Team1 To Score First & Win - Yes' },
  { id: 1351, nameTemplate: 'Team1 To Score First & Win - No' },
  { id: 1352, nameTemplate: 'Team2 To Score First & Win - Yes' },
  { id: 1353, nameTemplate: 'Team2 To Score First & Win - No' },
  { id: 1354, nameTemplate: 'Any Team To Score First & Win - Yes' },
  { id: 1355, nameTemplate: 'Any Team To Score First & Win - No' },
  { id: 1356, nameTemplate: '1st Field Goal - 3Way - Home Win' },
  { id: 1357, nameTemplate: '1st Field Goal - 3Way - Draw' },
  { id: 1358, nameTemplate: '1st Field Goal - 3Way - Away Win' },
  { id: 1359, nameTemplate: '1st Field Goal - 2Way - Home Win' },
  { id: 1360, nameTemplate: '1st Field Goal - 2Way - Away Win' },
  { id: 1361, nameTemplate: '1st Sack - 3Way - Home Win' },
  { id: 1362, nameTemplate: '1st Sack - 3Way - Draw' },
  { id: 1363, nameTemplate: '1st Sack - 3Way - Away Win' },
  { id: 1364, nameTemplate: '1st Home Run - 3Way - Home Win' },
  { id: 1365, nameTemplate: '1st Home Run - 3Way - Draw' },
  { id: 1366, nameTemplate: '1st Home Run - 3Way - Away Win' },
  { id: 1367, nameTemplate: 'Timeg Eg Eg' },
  { id: 1368, nameTemplate: 'Timeg Eg Eg N' },
  { id: 1369, nameTemplate: 'Team with Highest Scoring Period - Home Win' },
  { id: 1370, nameTemplate: 'Team with Highest Scoring Period - Draw' },
  { id: 1371, nameTemplate: 'Team with Highest Scoring Period - Away Win' },
  { id: 1372, nameTemplate: 'Highest Scoring Period - 1st Period' },
  { id: 1373, nameTemplate: 'Highest Scoring Period - 2nd Period' },
  { id: 1374, nameTemplate: 'Highest Scoring Period - 3rd Period' },
  { id: 1375, nameTemplate: 'Highest Scoring Period - Equal Halves' },
  { id: 1376, nameTemplate: 'Home Last Goalscorer - Yes' },
  { id: 1377, nameTemplate: 'Home Last Goalscorer - No' },
  { id: 1378, nameTemplate: 'Away Last Goalscorer - Yes' },
  { id: 1379, nameTemplate: 'Away Last Goalscorer - No' },
  { id: 1380, nameTemplate: 'Player Points - TO(%s)' },
  { id: 1381, nameTemplate: 'Player Points - TU(%s)' },
  { id: 1382, nameTemplate: 'Player Points - Exact(%s)' },
  { id: 1383, nameTemplate: 'Player Points - Exact(%s) - No' },
  { id: 1384, nameTemplate: 'Player First Card - Yes' },
  { id: 1385, nameTemplate: 'Player First Card - No' },
  { id: 1386, nameTemplate: 'Player Yellow Card - Yes' },
  { id: 1387, nameTemplate: 'Player Yellow Card - No' },
  { id: 1388, nameTemplate: 'Player Shots - TO(%s)' },
  { id: 1389, nameTemplate: 'Player Shots - TU(%s)' },
  { id: 1390, nameTemplate: 'Player Blocked Shots - TO(%s)' },
  { id: 1391, nameTemplate: 'Player Blocked Shots - TU(%s)' },
  { id: 1392, nameTemplate: 'Player To Score and Assist - Yes' },
  { id: 1393, nameTemplate: 'Player To Score and Assist - No' },
  { id: 1394, nameTemplate: 'Player Goal & Assist - TO(%s)' },
  { id: 1395, nameTemplate: 'Player Goal & Assist - TU(%s)' },
  { id: 1396, nameTemplate: 'Player Power Play Goal & Assist - TO(%s)' },
  { id: 1397, nameTemplate: 'Player Power Play Goal & Assist - TU(%s)' },
  { id: 1398, nameTemplate: 'Player To Score in OT - Yes' },
  { id: 1399, nameTemplate: 'Player To Score in OT - No' },
  { id: 1400, nameTemplate: 'Player Rebounds - Exact(%s)' },
  { id: 1401, nameTemplate: 'Player Rebounds - Exact(%s) - No' },
  { id: 1402, nameTemplate: 'Player 3-Points - Exact(%s)' },
  { id: 1403, nameTemplate: 'Player 3-Points - Exact(%s) - No' },
  { id: 1404, nameTemplate: 'Player Fouls - TO(%s)' },
  { id: 1405, nameTemplate: 'Player Fouls - TU(%s)' },
  { id: 1406, nameTemplate: 'Player Double Double - Yes' },
  { id: 1407, nameTemplate: 'Player Double Double - No' },
  { id: 1408, nameTemplate: 'Player Triple Double - Yes' },
  { id: 1409, nameTemplate: 'Player Triple Double - No' },
  { id: 1410, nameTemplate: 'Player Points & Assists - TO(%s)' },
  { id: 1411, nameTemplate: 'Player Points & Assists - TU(%s)' },
  { id: 1412, nameTemplate: 'Player Points & Rebounds - TO(%s)' },
  { id: 1413, nameTemplate: 'Player Points & Rebounds - TU(%s)' },
  { id: 1414, nameTemplate: 'Player Assists & Rebounds - TO(%s)' },
  { id: 1415, nameTemplate: 'Player Assists & Rebounds - TU(%s)' },
  { id: 1416, nameTemplate: 'Player Points & Assists & Rebounds - TO(%s)' },
  { id: 1417, nameTemplate: 'Player Points & Assists & Rebounds - TU(%s)' },
  { id: 1418, nameTemplate: 'Player Runs - Exact(%s)' },
  { id: 1419, nameTemplate: 'Player Runs - Exact(%s) - No' },
  { id: 1420, nameTemplate: 'Player Runs Batted In - TO(%s)' },
  { id: 1421, nameTemplate: 'Player Runs Batted In - TU(%s)' },
  { id: 1422, nameTemplate: 'Player Runs Batted In - Exact(%s)' },
  { id: 1423, nameTemplate: 'Player Runs Batted In - Exact(%s) - No' },
  { id: 1424, nameTemplate: 'Player Top Batsman - Yes' },
  { id: 1425, nameTemplate: 'Player Top Batsman - No' },
  { id: 1426, nameTemplate: 'Player Top Bowler - Yes' },
  { id: 1427, nameTemplate: 'Player Top Bowler - No' },
  { id: 1428, nameTemplate: 'Player Sixes - Exact(%s)' },
  { id: 1429, nameTemplate: 'Player Sixes - Exact(%s) - No' },
  { id: 1430, nameTemplate: 'Player Fours - Exact(%s)' },
  { id: 1431, nameTemplate: 'Player Fours - Exact(%s) - No' },
  { id: 1432, nameTemplate: 'Player Home First Touchdown - Yes' },
  { id: 1433, nameTemplate: 'Player Home First Touchdown - No' },
  { id: 1434, nameTemplate: 'Player Away First Touchdown - Yes' },
  { id: 1435, nameTemplate: 'Player Away First Touchdown - No' },
  { id: 1436, nameTemplate: 'Player Home Runs - Exact(%s)' },
  { id: 1437, nameTemplate: 'Player Home Runs - Exact(%s) - No' },
  { id: 1438, nameTemplate: 'Player Pitcher Earned Runs - TO(%s)' },
  { id: 1439, nameTemplate: 'Player Pitcher Earned Runs - TU(%s)' },
  { id: 1440, nameTemplate: 'Player Pitcher Strikeouts - Exact(%s)' },
  { id: 1441, nameTemplate: 'Player Pitcher Strikeouts - Exact(%s) - No' },
  { id: 1442, nameTemplate: 'Player Batter Strikeouts - TO(%s)' },
  { id: 1443, nameTemplate: 'Player Batter Strikeouts - TU(%s)' },
  { id: 1444, nameTemplate: 'Player Batter Strikeouts - Exact(%s)' },
  { id: 1445, nameTemplate: 'Player Batter Strikeouts - Exact(%s) - No' },
  { id: 1446, nameTemplate: 'Player Total Bases - Exact(%s)' },
  { id: 1447, nameTemplate: 'Player Total Bases - Exact(%s) - No' },
  { id: 1448, nameTemplate: 'Player Batter Walks - TO(%s)' },
  { id: 1449, nameTemplate: 'Player Batter Walks - TU(%s)' },
  { id: 1450, nameTemplate: 'Player Pitcher Walks Allowed - TO(%s)' },
  { id: 1451, nameTemplate: 'Player Pitcher Walks Allowed - TU(%s)' },
  { id: 1452, nameTemplate: 'Over(%s) - Player Hits Allowed' },
  { id: 1453, nameTemplate: 'Under(%s) - Player Hits Allowed' },
  { id: 1454, nameTemplate: 'Player Hits - Exact(%s)' },
  { id: 1455, nameTemplate: 'Player Hits - Exact(%s) - No' },
  { id: 1456, nameTemplate: 'Player Home First Tryscorer - Yes' },
  { id: 1457, nameTemplate: 'Player Home First Tryscorer - No' },
  { id: 1458, nameTemplate: 'Player Away First Tryscorer - Yes' },
  { id: 1459, nameTemplate: 'Player Away First Tryscorer - No' },
  { id: 1460, nameTemplate: 'Player Tries - Exact(%s)' },
  { id: 1461, nameTemplate: 'Player Tries - Exact(%s) - No' },
  { id: 1462, nameTemplate: 'Player Passing Touchdowns - Exact(%s)' },
  { id: 1463, nameTemplate: 'Player Passing Touchdowns - Exact(%s) - No' },
  { id: 1464, nameTemplate: 'Player Passing Yards - Exact(%s)' },
  { id: 1465, nameTemplate: 'Player Passing Yards - Exact(%s) - No' },
  { id: 1466, nameTemplate: 'Player Rushing Yards - Exact(%s)' },
  { id: 1467, nameTemplate: 'Player Rushing Yards - Exact(%s) - No' },
  { id: 1468, nameTemplate: 'Player Receiving Yards - TO(%s)' },
  { id: 1469, nameTemplate: 'Player Receiving Yards - TU(%s)' },
  { id: 1470, nameTemplate: 'Player Receiving Yards - Exact(%s)' },
  { id: 1471, nameTemplate: 'Player Receiving Yards - Exact(%s) - No' },
  { id: 1472, nameTemplate: 'Player Receptions - Exact(%s)' },
  { id: 1473, nameTemplate: 'Player Receptions - Exact(%s) - No' },
  { id: 1474, nameTemplate: 'Player Passing Attempts - Exact(%s)' },
  { id: 1475, nameTemplate: 'Player Passing Attempts - Exact(%s) - No' },
  { id: 1476, nameTemplate: 'Player Passing Completions - TO(%s)' },
  { id: 1477, nameTemplate: 'Player Passing Completions - TU(%s)' },
  { id: 1478, nameTemplate: 'Player Passing Completions - Exact(%s)' },
  { id: 1479, nameTemplate: 'Player Passing Completions - Exact(%s) - No' },
  { id: 1480, nameTemplate: 'Player Rushing Attempts - Exact(%s)' },
  { id: 1481, nameTemplate: 'Player Rushing Attempts - Exact(%s) - No' },
  { id: 1482, nameTemplate: 'Player Interceptions Thrown - TO(%s)' },
  { id: 1483, nameTemplate: 'Player Interceptions Thrown - TU(%s)' },
  { id: 1484, nameTemplate: 'Player Interceptions Thrown - Exact(%s)' },
  { id: 1485, nameTemplate: 'Player Interceptions Thrown - Exact(%s) - No' },
  { id: 1486, nameTemplate: 'Player Defensive Interceptions - TO(%s)' },
  { id: 1487, nameTemplate: 'Player Defensive Interceptions - TU(%s)' },
  { id: 1488, nameTemplate: 'Player Receiving & Rushing Yards - TO(%s)' },
  { id: 1489, nameTemplate: 'Player Receiving & Rushing Yards - TU(%s)' },
  { id: 1490, nameTemplate: 'Player Receiving & Rushing Yards - Exact(%s)' },
  {
    id: 1491,
    nameTemplate: 'Player Receiving & Rushing Yards - Exact(%s) - No',
  },
  { id: 1492, nameTemplate: 'Player Rushing & Passing Yards - TO(%s)' },
  { id: 1493, nameTemplate: 'Player Rushing & Passing Yards - TU(%s)' },
  { id: 1494, nameTemplate: 'Player Longest Pass Completion - TO(%s)' },
  { id: 1495, nameTemplate: 'Player Longest Pass Completion - TU(%s)' },
  { id: 1496, nameTemplate: 'Player Longest Rush - TO(%s)' },
  { id: 1497, nameTemplate: 'Player Longest Rush - TU(%s)' },
  { id: 1498, nameTemplate: 'Player Longest Reception - TO(%s)' },
  { id: 1499, nameTemplate: 'Player Longest Reception - TU(%s)' },
  { id: 1500, nameTemplate: 'Player Tackles - TO(%s)' },
  { id: 1501, nameTemplate: 'Player Tackles - TU(%s)' },
  { id: 1502, nameTemplate: 'Player Defensive Assists - TO(%s)' },
  { id: 1503, nameTemplate: 'Player Defensive Assists - TU(%s)' },
  { id: 1504, nameTemplate: 'Player Tackles & Assists - TO(%s)' },
  { id: 1505, nameTemplate: 'Player Tackles & Assists - TU(%s)' },
  { id: 1506, nameTemplate: 'Player Tackles & Assists - Exact(%s)' },
  { id: 1507, nameTemplate: 'Player Tackles & Assists - Exact(%s) - No' },
  { id: 1508, nameTemplate: 'Player Kicking Points - TO(%s)' },
  { id: 1509, nameTemplate: 'Player Kicking Points - TU(%s)' },
  { id: 1510, nameTemplate: 'Player Field Goals - TO(%s)' },
  { id: 1511, nameTemplate: 'Player Field Goals - TU(%s)' },
  { id: 1512, nameTemplate: 'Player To Record a Sack - Yes' },
  { id: 1513, nameTemplate: 'Player To Record a Sack - No' },
  { id: 1514, nameTemplate: 'Player Passes Completed - TO(%s)' },
  { id: 1515, nameTemplate: 'Player Passes Completed - TU(%s)' },
  { id: 1516, nameTemplate: 'Player Offsides - TO(%s)' },
  { id: 1517, nameTemplate: 'Player Offsides - TU(%s)' },
  { id: 1518, nameTemplate: 'Player Saves - TO(%s)' },
  { id: 1519, nameTemplate: 'Player Saves - TU(%s)' },
  { id: 1520, nameTemplate: 'Player Headed Goal - Yes' },
  { id: 1521, nameTemplate: 'Player Headed Goal - No' },
  { id: 1522, nameTemplate: 'Player Outside the Box Goal - Yes' },
  { id: 1523, nameTemplate: 'Player Outside the Box Goal - No' },
  { id: 1524, nameTemplate: 'Player Disposals - TO(%s)' },
  { id: 1525, nameTemplate: 'Player Disposals - TU(%s)' },
  { id: 1526, nameTemplate: 'Player Hits & Runs & RBIs - TO(%s)' },
  { id: 1527, nameTemplate: 'Player Hits & Runs & RBIs - TU(%s)' },
  { id: 1528, nameTemplate: 'Cnr Eg Eg N' },
  { id: 1529, nameTemplate: 'Cnr Eg1 Eg N' },
  { id: 1530, nameTemplate: 'Cnr Eg2 Eg N' },
  { id: 1531, nameTemplate: 'Yc Eg Eg N' },
  { id: 1532, nameTemplate: 'Yc Eg1 Eg N' },
  { id: 1533, nameTemplate: 'Yc Eg2 Eg N' },
  { id: 1534, nameTemplate: 'Card Eg Eg N' },
  { id: 1535, nameTemplate: 'Card Eg1 Eg N' },
  { id: 1536, nameTemplate: 'Card Eg2 Eg N' },
  { id: 1537, nameTemplate: 'Bp Eg Eg N' },
  { id: 1538, nameTemplate: 'Bp Eg1 Eg N' },
  { id: 1539, nameTemplate: 'Bp Eg2 Eg N' },
];
